// Localization Dictionary
export const translations = {
  en: {
    game_subtitle: "SUNSET SURVIVAL & MINING",
    game_desc: "Explore a low-poly tropical island, mine underground tunnels in search of gold, and avoid drowning in the open ocean. Dig through rocks using your pickaxe and repair the boat.",
    alpha_badge: "ALPHA PROTOTYPE v0.057",
    rotate_warning_title: "PLEASE ROTATE DEVICE",
    rotate_warning_desc: "This game is designed to be played in landscape mode (horizontal) only.",
    start_btn: "START ENGINE",
    controls_title: "CONTROL TELEMETRY",
    ctrl_mv: "FPS Movement",
    ctrl_look: "Look Around",
    ctrl_dig: "Dig / Attack",
    ctrl_jump: "Jump / Swim Up",
    ctrl_harvest: "Harvest Ore / Resource",
    ctrl_switch: "Switch Tool",
    hud_objective: "OBJECTIVE",
    hud_compass: "COMPASS",
    hud_distance: "DISTANCE",
    hud_health: "HEALTH",
    hud_energy: "ENERGY",
    hud_hydration: "HYDRATION",
    obj_initial: "Collect ore for boat repairs",
    obj_progress: "Collect ore for boat repairs ({val}/5)",
    obj_complete: "Objective Completed! Boat repaired.",
    interact_harvest: "PRESS E TO HARVEST ORE",
    interact_board: "PRESS E TO READ FEEDBACK BOARD",
    board_title: "COMMUNITY FEEDBACK TERMINAL",
    board_placeholder: "Enter your message here...",
    board_submit: "TRANSMIT",
    board_close: "CLOSE",
    msg_mined: "Mined Gold Ore! Pick it up.",
    msg_depleted: "Ore Deposit Depleted!",
    msg_collected: "+1 Gold Ore",
    msg_goal_complete: "Survival Goal Complete!",
    interact_harvest_wood: "PRESS E TO HARVEST WOOD",
    msg_chopped: "Chop!",
    msg_tree_felled: "Tree felled!",
    msg_collected_wood: "+1 Wood",
    hotbar: {
      spear: "Spear",
      axe: "Axe",
      water: "Water",
      leaves: "Leaves",
      rope: "Rope",
      wood: "Wood",
      pickaxe: "Pickaxe",
      stone: "Stone",
      ore: "Ore"
    },
    confirm_title: "QUIT GAME?",
    confirm_desc: "Are you sure you want to return to the main menu? Your progress will be lost.",
    confirm_yes: "YES, EXIT",
    confirm_no: "NO, CONTINUE",
    inv_title: "INVENTORY",
    inv_my_bag: "MY BAG",
    inv_crafting: "CRAFTING STATION",
    inv_character: "CHARACTER",
    inv_stat_energy: "Stamina Decay",
    inv_stat_hydration: "Hydration Decay",
    inv_stat_speed: "Speed Bonus",
    "inv.straw_hat": "Straw Hat",
    "inv.explorer_vest": "Explorer Vest",
    "inv.grass_pants": "Grass Pants",
    "inv.wooden_boots": "Wooden Boots",
    "inv.empty": "[Empty]",
    "recipe.rope": "3 Leaves",
    "recipe.straw_hat": "6 Leaves, 2 Ropes",
    "recipe.grass_pants": "8 Leaves, 3 Ropes",
    "recipe.wooden_boots": "4 Wood, 2 Ropes",
    "inv.raw_fish": "Raw Fish",
    "inv.worm": "Worm",
    "inv.raw_crab": "Raw Crab",
    "inv.cooked_meat": "Cooked Meat",
    "inv.campfire": "Campfire",
    "recipe.campfire": "4 Wood, 2 Stone",
    interact_cook: "PRESS E TO COOK MEAT",
    interact_harvest_crab: "PRESS E TO HARVEST RAW CRAB",
    interact_harvest_fish: "PRESS E TO HARVEST RAW FISH",
    interact_harvest_cooked: "PRESS E TO HARVEST COOKED MEAT",
    interact_harvest_worm: "PRESS E TO COLLECT WORM",
    msg_hunted_crab: "Hunted Crab!",
    msg_hunted_fish: "Hunted Fish!",
    msg_collected_worm: "+1 Worm",
    msg_cooked_crab: "Cooked Crab Meat!",
    msg_cooked_fish: "Cooked Fish Meat!",
    msg_placed_campfire: "Placed Campfire!",
    msg_ate_cooked: "Ate cooked meat! +20 HP, +40 Energy",
    msg_ate_raw: "Ate raw food! Drained 5 HP, 10 Energy",
    msg_collected_raw_crab: "+1 Raw Crab",
    msg_collected_raw_fish: "+1 Raw Fish",
    msg_collected_cooked: "+1 Cooked Meat",
    "inv.stick": "Stick",
    "inv.cane": "Cane",
    interact_harvest_stick: "PRESS E TO COLLECT STICK",
    interact_harvest_cane: "PRESS E TO COLLECT CANE",
    msg_cane_hit: "Hit cane!",
    msg_cane_broken: "Cane broken!",
    msg_collected_stick: "+1 Stick",
    msg_collected_cane: "+1 Cane",
    msg_already_hydrated: "Already hydrated!",
    msg_drank_water: "Drank water! +30 Hydration",
    interact_cook_fuel: "PRESS E TO COOK MEAT / PRESS F TO ADD FUEL (Fuel: {fuel}s)",
    interact_fuel_only: "PRESS F TO ADD FUEL (Fuel: {fuel}s)",
    interact_relight: "PRESS F TO LIGHT FIRE (2 Stones & 1 Leaf)",
    msg_fire_out: "FIRE IS OUT (Needs 2 Stones & 1 Leaf)",
    msg_fire_is_out: "The fire is out! Add fuel/stones to light it.",
    msg_fire_full: "Campfire fuel capacity is full!",
    msg_added_fuel: "Added fuel! ({type}: +{amount}s)",
    msg_lit_fire_spark: "Sparked the stones and lit the fire with leaves!",
    msg_no_fuel: "No fuel in inventory! (Need Leaves, Sticks, or Wood)",
    msg_no_ignition: "Need 2 Stones and 1 Leaf to spark the fire!",
    msg_world_edge: "Reached the edge of the world!",
    interact_harvest_log: "PRESS E TO COLLECT FALLEN LOG",
    interact_harvest_liana: "PRESS E TO COLLECT LIANA",
    msg_collected_log: "+1 Wood (Fallen Log)",
    msg_collected_liana: "+1 Rope (Liana)",
    msg_need_mats_raft: "Construct Raft (Need 4 Logs, 2 Lianas, 2 Sticks)",
    msg_press_construct: "Press E to Construct Raft",
    msg_press_sail: "Press E to Sail Raft",
    msg_press_disembark: "Press E to Disembark",
    msg_raft_repaired: "Raft Constructed! Ready to sail.",
    msg_extreme_heat: "🌡️ EXTREME HEAT: Hydration draining faster!",
    msg_in_lava: "🔥 IN LAVA! TAKING DAMAGE! 🔥",
    obj_sail_explore: "Sail and explore other islands",
    inv_slot_head: "HEAD",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "LEGS",
    inv_slot_feet: "FEET",
    inv_slot_right_hand: "RIGHT HAND",
    inv_slot_left_hand: "LEFT HAND",
    "inv.fishing_rod": "Fishing Rod",
    "recipe.fishing_rod": "2 Sticks, 2 Ropes",
    "inv.egg": "Egg",
    "inv.cooked_egg": "Cooked Egg",
    interact_harvest_egg: "PRESS E TO COLLECT EGG",
    interact_harvest_cooked_egg: "PRESS E TO COLLECT COOKED EGG",
    interact_feed_hen: "PRESS E TO FEED ROSITA (1 Worm)",
    msg_hen_laid_egg: "Rosita laid an egg!",
    msg_collected_egg: "+1 Egg",
    msg_collected_cooked_egg: "+1 Cooked Egg",
    msg_cooked_egg: "Cooked Egg!",
    msg_ate_cooked_egg: "Ate cooked egg! +15 HP, +30 Energy, +5 Hydration",
    msg_fishing_wait: "Fishing... wait for a bite!",
    msg_fishing_bite: "A FISH IS BITING! CLICK TO REEL IN!",
    msg_fishing_caught: "Caught a fish!",
    msg_fishing_escaped: "The fish got away!",
    msg_fishing_early: "Reeled in too early!",
    msg_fishing_cancelled: "Fishing cancelled!",
    msg_no_bait: "Needs 1 Worm as bait! Collect them from the dead seagull.",
    "inv.torch": "Hand Torch",
    "recipe.torch": "1 Stick, 2 Leaves",
    "inv.berries": "Wild Berries",
    interact_harvest_berries: "PRESS E TO GATHER BERRIES",
    msg_collected_berries: "+3 Wild Berries",
    msg_ate_berries: "Ate wild berries! +5 HP, +15 Energy, +10 Hydration"
  },
  ja: {
    game_subtitle: "夕暮れの生存と採掘",
    game_desc: "ローポリの熱帯の島を探索し、金を求めて地下トンネルを採掘し、開けた海でおぼれないようにしてください。ピッケルで岩を掘り進み、ボートを修理しましょう。",
    alpha_badge: "アルファプロトタイプ v0.057",
    rotate_warning_title: "画面を横にしてください",
    rotate_warning_desc: "このゲームは横画面（ランドスケープ）専用です。",
    start_btn: "エンジン始動",
    controls_title: "操作テレメトリー",
    ctrl_mv: "FPS移動",
    ctrl_look: "周囲を見回す",
    ctrl_dig: "掘る / 攻撃",
    ctrl_jump: "ジャンプ / 浮上する",
    ctrl_harvest: "鉱石・資源 of 回収",
    ctrl_switch: "ツールの切り替え",
    hud_objective: "目標",
    hud_compass: "コンパス",
    hud_distance: "距離",
    hud_health: "体力",
    hud_energy: "スタミナ",
    hud_hydration: "水分",
    obj_initial: "ボート修理用の鉱石を収集する",
    obj_progress: "ボート修理用の鉱石を収集する ({val}/5)",
    obj_complete: "目標達成！ボートが修理されました。",
    interact_harvest: "Eキーで鉱石を回収",
    interact_board: "Eキーで掲示板を読む",
    board_title: "コミュニティ・フィードバック・ターミナル",
    board_placeholder: "メッセージを入力してください...",
    board_submit: "送信する",
    board_close: "閉じる",
    msg_mined: "金鉱石を採掘しました！拾ってください。",
    msg_depleted: "鉱床が枯渇しました！",
    msg_collected: "+1 金鉱石",
    msg_goal_complete: "サバイバルゴール達成！",
    interact_harvest_wood: "Eキーで木材を回収",
    msg_chopped: "チョップ！",
    msg_tree_felled: "木が倒れました！",
    msg_collected_wood: "+1 木材",
    hotbar: {
      spear: "槍",
      axe: "斧",
      water: "水",
      leaves: "葉",
      rope: "ロープ",
      wood: "木",
      pickaxe: "ツルハシ",
      stone: "石",
      ore: "鉱石"
    },
    confirm_title: "終了しますか？",
    confirm_desc: "メインメニューに戻りますか？進行状況は失われます。",
    confirm_yes: "はい、終了します",
    confirm_no: "いいえ、続けます",
    inv_title: "インベントリ",
    inv_my_bag: "バッグ",
    inv_crafting: "クラフトステーション",
    inv_character: "キャラクター",
    inv_stat_energy: "スタミナ消費",
    inv_stat_hydration: "水分消費",
    inv_stat_speed: "速度ボーナス",
    "inv.straw_hat": "麦わら帽子",
    "inv.explorer_vest": "探検家のベスト",
    "inv.grass_pants": "草のズボン",
    "inv.wooden_boots": "木製のブーツ",
    "inv.empty": "[空]",
    "recipe.rope": "葉 x3",
    "recipe.straw_hat": "葉 x6, ロープ x2",
    "recipe.grass_pants": "葉 x8, ロープ x3",
    "recipe.wooden_boots": "木材 x4, ロープ x2",
    inv_slot_head: "頭部",
    inv_slot_torso: "胸部",
    inv_slot_legs: "脚部",
    inv_slot_feet: "足部",
    inv_slot_right_hand: "右手",
    inv_slot_left_hand: "左手"
  },
  es: {
    game_subtitle: "SUPERVIVENCIA Y MINERÍA AL ATARDECER",
    game_desc: "Explora una isla tropical low-poly, cava túneles subterráneos en busca de oro y evita ahogarte en el océano abierto. Hazte camino entre las rocas usando tu pico y repara el barco.",
    alpha_badge: "PROTOTIPO ALPHA v0.057",
    rotate_warning_title: "POR FAVOR ROTAR DISPOSITIVO",
    rotate_warning_desc: "Este juego está diseñado para jugarse únicamente en modo horizontal.",
    start_btn: "ARRANCAR MOTOR",
    controls_title: "TELEMETRÍA DE CONTROL",
    ctrl_mv: "Movimiento FPS",
    ctrl_look: "Mirar alrededor",
    ctrl_dig: "Cavar / Atacar",
    ctrl_jump: "Saltar / Nadar arriba",
    ctrl_harvest: "Recoger oro / recursos",
    ctrl_switch: "Cambiar herramienta",
    hud_objective: "OBJETIVO",
    hud_compass: "BRÚJULA",
    hud_distance: "DISTANCIA",
    hud_health: "SALUD",
    hud_energy: "ENERGÍA",
    hud_hydration: "HIDRATACIÓN",
    obj_initial: "Recoge mineral para reparar el barco",
    obj_progress: "Recoge mineral para reparar el barco ({val}/5)",
    obj_complete: "¡Objetivo completado! Barco reparado.",
    interact_harvest: "PULSA E PARA RECOGER MINERAL",
    interact_board: "PULSA E PARA LEER EL TABLÓN",
    board_title: "TERMINAL DE FEEDBACK DE LA COMUNIDAD",
    board_placeholder: "Escribe tu mensaje aquí...",
    board_submit: "TRANSMITIR",
    board_close: "CERRAR",
    msg_mined: "¡Mineral de oro extraído! Recógelo.",
    msg_depleted: "¡Yacimiento de mineral agotado!",
    msg_collected: "+1 Mineral de oro",
    msg_goal_complete: "¡Meta de supervivencia completada!",
    interact_harvest_wood: "PRESIONA E PARA RECOLECTAR MADERA",
    msg_chopped: "¡Tajo!",
    msg_tree_felled: "¡Árbol talado!",
    msg_collected_wood: "+1 Madera",
    hotbar: {
      spear: "Lanza",
      axe: "Hacha",
      water: "Agua",
      leaves: "Hojas",
      rope: "Cuerda",
      wood: "Madera",
      pickaxe: "Pico",
      stone: "Piedra",
      ore: "Mineral"
    },
    confirm_title: "¿ABANDONAR PARTIDA?",
    confirm_desc: "¿Seguro que quieres volver al menú principal? Se perderá tu progreso.",
    confirm_yes: "SÍ, SALIR",
    confirm_no: "NO, CONTINUAR",
    inv_title: "INVENTARIO",
    inv_my_bag: "MI BOLSA",
    inv_crafting: "ESTACIÓN DE ARTESANÍA",
    inv_character: "PERSONAJE",
    inv_stat_energy: "Consumo de Energía",
    inv_stat_hydration: "Consumo de Hidratación",
    inv_stat_speed: "Bono de Velocidad",
    "inv.straw_hat": "Sombrero de Paja",
    "inv.explorer_vest": "Chaleco de Explorador",
    "inv.grass_pants": "Pantalones de Hierba",
    "inv.wooden_boots": "Botas de Madera",
    "inv.empty": "[Vacío]",
    "recipe.rope": "3 Hojas",
    "recipe.straw_hat": "6 Hojas, 2 Cuerdas",
    "recipe.grass_pants": "8 Hojas, 3 Cuerdas",
    "recipe.wooden_boots": "4 Madera, 2 Cuerdas",
    inv_slot_head: "CABEZA",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "PIERNAS",
    inv_slot_feet: "PIES",
    inv_slot_right_hand: "MANO DERECHA",
    inv_slot_left_hand: "MANO IZQUIERDA"
  },
  fr: {
    game_subtitle: "SURVIE ET MINAGE AU CRÉPUSCULE",
    game_desc: "Explorez une île tropicale low-poly, creusez des tunnels souterrains à la recherche d'or et évitez de vous noyer en pleine mer. Frayez-vous un chemin à travers les roches à l'aide de votre pioche et réparez le bateau.",
    alpha_badge: "PROTOTYPE ALPHA v0.057",
    rotate_warning_title: "VEUILLEZ PIVOTER L'APPAREIL",
    rotate_warning_desc: "Ce jeu est conçu pour être joué en mode paysage (horizontal) uniquement.",
    start_btn: "DÉMARRER MOTEUR",
    controls_title: "TÉLÉMÉTRIE DES COMMANDES",
    ctrl_mv: "Mouvement FPS",
    ctrl_look: "Regarder autour",
    ctrl_dig: "Creuser / Attaquer",
    ctrl_jump: "Sauter / Nager vers le haut",
    ctrl_harvest: "Récolter minerai / ressources",
    ctrl_switch: "Changer d'outil",
    hud_objective: "OBJECTIF",
    hud_compass: "BOUSSOLE",
    hud_distance: "DISTANCE",
    hud_health: "SANTÉ",
    hud_energy: "ÉNERGIE",
    hud_hydration: "HYDRATION",
    obj_initial: "Collecter du minerai pour réparer le bateau",
    obj_progress: "Collecter du minerai pour réparer le bateau ({val}/5)",
    obj_complete: "Objectif atteint ! Bateau réparé.",
    interact_harvest: "APPUYER SUR E POUR RÉCOLTER LE MINERAI",
    interact_board: "APPUYER SUR E POUR LIRE LE TABLEAU",
    board_title: "CONSOLE DE FEEDBACK COMMUNAUTAIRE",
    board_placeholder: "Saisissez votre message ici...",
    board_submit: "TRANSMETTRE",
    board_close: "FERMER",
    msg_mined: "Minerai d'or extrait ! Ramassez-le.",
    msg_depleted: "Gisement de minerai épuisé !",
    msg_collected: "+1 Minerai d'or",
    msg_goal_complete: "Objectif de survie atteint !",
    interact_harvest_wood: "APPUYEZ SUR E POUR RAMASSER LE BOIS",
    msg_chopped: "Coupe !",
    msg_tree_felled: "Arbre abattu !",
    msg_collected_wood: "+1 Bois",
    hotbar: {
      spear: "Lance",
      axe: "Hache",
      water: "Eau",
      leaves: "Feuilles",
      rope: "Corde",
      wood: "Bois",
      pickaxe: "Pioche",
      stone: "Pierre",
      ore: "Minerai"
    },
    confirm_title: "QUITTER LA PARTIE ?",
    confirm_desc: "Voulez-vous vraiment retourner au menu principal ? Votre progression sera perdue.",
    confirm_yes: "OUI, QUITTER",
    confirm_no: "NON, CONTINUER",
    inv_title: "INVENTAIRE",
    inv_my_bag: "MON SAC",
    inv_crafting: "STATION D'ARTISANAT",
    inv_character: "PERSONNAGE",
    inv_stat_energy: "Consommation d'Énergie",
    inv_stat_hydration: "Consommation d'Hydratation",
    inv_stat_speed: "Bonus de Vitesse",
    "inv.straw_hat": "Chapeau de Paille",
    "inv.explorer_vest": "Gilet d'Explorateur",
    "inv.grass_pants": "Pantalon d'Herbe",
    "inv.wooden_boots": "Bottes en Bois",
    "inv.empty": "[Vide]",
    "recipe.rope": "3 Feuilles",
    "recipe.straw_hat": "6 Feuilles, 2 Cordes",
    "recipe.grass_pants": "8 Feuilles, 3 Cordes",
    "recipe.wooden_boots": "4 Bois, 2 Cordes",
    inv_slot_head: "TÊTE",
    inv_slot_torso: "TORSE",
    inv_slot_legs: "JAMBES",
    inv_slot_feet: "PIEDS",
    inv_slot_right_hand: "MAIN DROITE",
    inv_slot_left_hand: "MAIN GAUCHE"
  },
  de: {
    game_subtitle: "ÜBERLEBEN UND BERGBAU IM SONNENUNTERGANG",
    game_desc: "Erkunde eine Low-Poly-Tropeninsel, grabe unterirdische Tunnel auf der Suche nach Gold und vermeide es, im offenen Ozean zu ertrinken. Bahne dir mit deiner Spitzhacke den Weg durch die Felsen und repariere das Boot.",
    alpha_badge: "ALPHA-PROTOTYP v0.057",
    rotate_warning_title: "GERÄT DREHEN",
    rotate_warning_desc: "Dieses Spiel kann nur im Querformat (horizontal) gespielt werden.",
    start_btn: "MOTOR STARTEN",
    controls_title: "STEUERUNGSTELEMETRIE",
    ctrl_mv: "FPS-Bewegung",
    ctrl_look: "Umschauen",
    ctrl_dig: "Graben / Angreifen",
    ctrl_jump: "Springen / Aufschwimmen",
    ctrl_harvest: "Erz / Ressourcen sammeln",
    ctrl_switch: "Werkzeug wechseln",
    hud_objective: "ZIEL",
    hud_compass: "KOMPASS",
    hud_distance: "ENTFERNUNG",
    hud_health: "GESUNDHEIT",
    hud_energy: "ENERGIE",
    hud_hydration: "HYDRATION",
    obj_initial: "Sammle Erz für Bootsreparaturen",
    obj_progress: "Sammle Erz für Bootsreparaturen ({val}/5)",
    obj_complete: "Ziel erreicht! Boot repariert.",
    interact_harvest: "DRÜCKE E, UM ERZ ZU SAMMELN",
    interact_board: "DRÜCKE E, UM DAS TABLEAU ZU LESEN",
    board_title: "COMMUNITY-FEEDBACK-TERMINAL",
    board_placeholder: "Geben Sie Ihre Nachricht ein...",
    board_submit: "SENDEN",
    board_close: "SCHLIESSEN",
    msg_mined: "Golderz abgebaut! Sammle es auf.",
    msg_depleted: "Erzvorkommen erschöpft!",
    msg_collected: "+1 Golderz",
    msg_goal_complete: "Überlebensziel erreicht!",
    interact_harvest_wood: "DRÜCKE E UM HOLZ ZU SAMMELN",
    msg_chopped: "Hack!",
    msg_tree_felled: "Baum gefällt!",
    msg_collected_wood: "+1 Holz",
    hotbar: {
      spear: "Speer",
      axe: "Axt",
      water: "Wasser",
      leaves: "Blätter",
      rope: "Seil",
      wood: "Holz",
      pickaxe: "Spitzhacke",
      stone: "Stein",
      ore: "Erz"
    },
    confirm_title: "SPIEL VERLASSEN?",
    confirm_desc: "Möchtest du wirklich zum Hauptmenü zurückkehren? Dein Fortschritt geht verloren.",
    confirm_yes: "JA, BEENDEN",
    confirm_no: "NEIN, WEITER",
    inv_title: "INVENTAR",
    inv_my_bag: "MEINE TASCHE",
    inv_crafting: "HANDWERKSSTATION",
    inv_character: "CHARAKTER",
    inv_stat_energy: "Ausdauer-Abfall",
    inv_stat_hydration: "Hydratations-Abfall",
    inv_stat_speed: "Geschwindigkeitsbonus",
    "inv.straw_hat": "Strohhut",
    "inv.explorer_vest": "Entdeckerweste",
    "inv.grass_pants": "Gras-Hose",
    "inv.wooden_boots": "Holzstiefel",
    "inv.empty": "[Leer]",
    "recipe.rope": "3 Blätter",
    "recipe.straw_hat": "6 Blätter, 2 Seile",
    "recipe.grass_pants": "8 Blätter, 3 Seile",
    "recipe.wooden_boots": "4 Holz, 2 Seile",
    inv_slot_head: "KOPF",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "BEINE",
    inv_slot_feet: "FÜSSE",
    inv_slot_right_hand: "RECHTE HAND",
    inv_slot_left_hand: "LINKE HAND"
  },
  pt: {
    game_subtitle: "SOBREVIVÊNCIA E MINERAÇÃO AO PÔR DO SOL",
    game_desc: "Explore uma ilha tropical low-poly, cave túneis subterrâneos em busca de oro e evite se afogar no oceano aberto. Abra caminho pelas rochas usando sua picareta e conserte o barco.",
    alpha_badge: "PROTÓTIPO ALPHA v0.057",
    rotate_warning_title: "POR FAVOR ROTE O DISPOSITIVO",
    rotate_warning_desc: "Este jogo foi projetato para ser jogado apenas no modo paisagem (horizontal).",
    start_btn: "LIGAR MOTOR",
    controls_title: "TELEMETRIA DE CONTROLE",
    ctrl_mv: "Movimento FPS",
    ctrl_look: "Olhar ao redor",
    ctrl_dig: "Cavar / Atacar",
    ctrl_jump: "Saltar / Nadar para cima",
    ctrl_harvest: "Coletar minério / recursos",
    ctrl_switch: "Mudar ferramenta",
    hud_objective: "OBJETIVO",
    hud_compass: "BÚSSOLA",
    hud_distance: "DISTÂNCIA",
    hud_health: "SAÚDE",
    hud_energy: "ENERGIA",
    hud_hydration: "HIDRATAÇÃO",
    obj_initial: "Colete minério para consertar o barco",
    obj_progress: "Colete minério para consertar o barco ({val}/5)",
    obj_complete: "Objetivo Concluído! Barco consertado.",
    interact_harvest: "PRESSIONE E PARA COLETAR MINÉRIO",
    interact_board: "PRESSIONE E PARA LER O QUADRO",
    board_title: "TERMINAL DE FEEDBACK DA COMUNIDADE",
    board_placeholder: "Digite sua mensagem aqui...",
    board_submit: "TRANSMITIR",
    board_close: "FECHAR",
    msg_mined: "Minério de ouro extraído! Colete-o.",
    msg_depleted: "Depósito de minério esgotado!",
    msg_collected: "+1 Minério de ouro",
    msg_goal_complete: "Meta de Sobrevivência Concluída!",
    interact_harvest_wood: "PRESSIONE E PARA COLETAR MADEIRA",
    msg_chopped: "Golpe!",
    msg_tree_felled: "Árvore derrubada!",
    msg_collected_wood: "+1 Madeira",
    hotbar: {
      spear: "Lança",
      axe: "Machado",
      water: "Água",
      leaves: "Folhas",
      rope: "Corda",
      wood: "Madeira",
      pickaxe: "Picareta",
      stone: "Pedra",
      ore: "Minério"
    },
    confirm_title: "ABANDONAR PARTIDA?",
    confirm_desc: "Tem certeza de que deseja voltar ao menu principal? Seu progresso será perdido.",
    confirm_yes: "SIM, SAIR",
    confirm_no: "NÃO, CONTINUAR",
    inv_title: "INVENTÁRIO",
    inv_my_bag: "MINHA MOCHILA",
    inv_crafting: "ESTAÇÃO DE CRIAÇÃO",
    inv_character: "PERSONAGEM",
    inv_stat_energy: "Consumo de Energia",
    inv_stat_hydration: "Consumo de Hidratação",
    inv_stat_speed: "Bônus de Velocidade",
    "inv.straw_hat": "Chapéu de Palha",
    "inv.explorer_vest": "Colete de Explorador",
    "inv.grass_pants": "Calças de Grama",
    "inv.wooden_boots": "Botas de Madeira",
    "inv.empty": "[Vazio]",
    "recipe.rope": "3 Folhas",
    "recipe.straw_hat": "6 Folhas, 2 Cordas",
    "recipe.grass_pants": "8 Folhas, 3 Cordas",
    "recipe.wooden_boots": "4 Madeira, 2 Cordas",
    inv_slot_head: "CABEÇA",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "PERNAS",
    inv_slot_feet: "PÉS",
    inv_slot_right_hand: "MÃO DIREITA",
    inv_slot_left_hand: "MÃO ESQUERDA"
  },
  it: {
    game_subtitle: "SOPRAVVIVENZA E MINIERA AL TRAMONTO",
    game_desc: "Esplora un'isola tropicale low-poly, scava gallerie sotterranee alla ricerca di oro ed evita di affogare nell'oceano aperto. Fatti strada tra le rocce usando il tuo piccone e ripara la barca.",
    alpha_badge: "PROTOTIPO ALPHA v0.057",
    rotate_warning_title: "RUOTA IL DISPOSITIVO",
    rotate_warning_desc: "Questo gioco è progettato per essere giocato solo in modalità orizzontale.",
    start_btn: "AVVIA MOTORE",
    controls_title: "TELEMETRIA COMANDI",
    ctrl_mv: "Movimento FPS",
    ctrl_look: "Guarda in giro",
    ctrl_dig: "Scava / Attacca",
    ctrl_jump: "Salta / Nuota su",
    ctrl_harvest: "Raccogli oro / risorse",
    ctrl_switch: "Cambia strumento",
    hud_objective: "OBIETTIVO",
    hud_compass: "BUSSOLA",
    hud_distance: "DISTANZA",
    hud_health: "SALUTE",
    hud_energy: "ENERGIA",
    hud_hydration: "IDRATAZIONE",
    obj_initial: "Raccogli oro per riparare la barca",
    obj_progress: "Raccogli oro per riparare la barca ({val}/5)",
    obj_complete: "Obiettivo Completato! Barca riparata.",
    interact_harvest: "PREMI E PER RACCOGLIERE ORO",
    interact_board: "PREMI E PER LEGGERE LA LAVAGNA",
    board_title: "TERMINALE FEEDBACK DELLA COMMUNITY",
    board_placeholder: "Scrivi il tuo messaggio qui...",
    board_submit: "INVIA",
    board_close: "CHIUDI",
    msg_mined: "Oro estratto! Raccolto.",
    msg_depleted: "Giacimento esaurito!",
    msg_collected: "+1 Oro",
    msg_goal_complete: "Obiettivo Sopravvivenza Completato!",
    interact_harvest_wood: "PREMI E PER RACCOGLIERE IL LEGNO",
    msg_chopped: "Taglio!",
    msg_tree_felled: "Albero abbattuto!",
    msg_collected_wood: "+1 Legno",
    hotbar: {
      spear: "Lancia",
      axe: "Accetta",
      water: "Acqua",
      leaves: "Foglie",
      rope: "Corda",
      wood: "Legno",
      pickaxe: "Piccone",
      stone: "Pietra",
      ore: "Oro"
    },
    confirm_title: "ABBANDONARE LA PARTITA?",
    confirm_desc: "Sei sicuro di voler tornare al menu principale? I tuoi progressi andranno perduti.",
    confirm_yes: "SÌ, ESCI",
    confirm_no: "NO, CONTINUA",
    inv_title: "INVENTARIO",
    inv_my_bag: "BORSA",
    inv_crafting: "ARTIGIANATO",
    inv_character: "PERSONAGGIO",
    inv_stat_energy: "Consumo Energia",
    inv_stat_hydration: "Consumo Acqua",
    inv_stat_speed: "Bonus Velocità",
    "inv.straw_hat": "Cappello di Paglia",
    "inv.explorer_vest": "Gilet del Esploratore",
    "inv.grass_pants": "Pantaloni d'Erba",
    "inv.wooden_boots": "Stivali di Legno",
    "inv.empty": "[Vuoto]",
    "recipe.rope": "3 Foglie",
    "recipe.straw_hat": "6 Foglie, 2 Corde",
    "recipe.grass_pants": "8 Foglie, 3 Corde",
    "recipe.wooden_boots": "4 Legno, 2 Corde",
    "inv.raw_fish": "Pesce Crudo",
    "inv.worm": "Verme",
    "inv.raw_crab": "Granchio Crudo",
    "inv.cooked_meat": "Carne Cotta",
    "inv.campfire": "Falò",
    "recipe.campfire": "4 Legno, 2 Pietra",
    interact_cook: "PREMI E PER CUOCERE LA CARNE",
    interact_harvest_crab: "PREMI E PER RACCOGLIERE IL GRANCHIO CRUDO",
    interact_harvest_fish: "PREMI E PER RACCOGLIERE IL PESCE CRUDO",
    interact_harvest_cooked: "PREMI E PER RACCOGLIERE LA CARNE COTTA",
    interact_harvest_worm: "PREMI E PER RACCOGLIERE IL VERME",
    msg_hunted_crab: "Cacciato Granchio!",
    msg_hunted_fish: "Cacciato Pesce!",
    msg_collected_worm: "+1 Verme",
    msg_cooked_crab: "Carne di Granchio Cotta!",
    msg_cooked_fish: "Carne di Pesce Cotta!",
    msg_placed_campfire: "Falò Posizionato!",
    msg_ate_cooked: "Mangiata carne cotta! +20 HP, +40 Energia",
    msg_ate_raw: "Mangiato cibo crudo! Persi 5 HP, 10 Energia",
    msg_collected_raw_crab: "+1 Granchio Crudo",
    msg_collected_raw_fish: "+1 Pesce Crudo",
    msg_collected_cooked: "+1 Carne Cotta",
    "inv.stick": "Bastone",
    "inv.cane": "Canna",
    interact_harvest_stick: "PREMI E PER RACCOGLIERE IL BASTONE",
    interact_harvest_cane: "PREMI E PER RACCOGLIERE LA CANNA",
    msg_cane_hit: "Colpita canna!",
    msg_cane_broken: "Canna spezzata!",
    msg_collected_stick: "+1 Bastone",
    msg_collected_cane: "+1 Canna",
    msg_already_hydrated: "Sei già idratato!",
    msg_drank_water: "Hai bevuto acqua! +30 Idratazione",
    interact_cook_fuel: "PREMI E PER CUOCERE / PREMI F PER AGGIUNGERE LEGNA (Fuoco: {fuel}s)",
    interact_fuel_only: "PREMI F PER AGGIUNGERE LEGNA (Fuoco: {fuel}s)",
    interact_relight: "PREMI F PER ACCENDERE (2 Pietre & 1 Foglia)",
    msg_fire_out: "IL FUOCO È SPENTO (Servono 2 Pietre & 1 Foglia)",
    msg_fire_is_out: "Il fuoco è spento! Servono pietre e combustibile per accenderlo.",
    msg_fire_full: "La capacità di legna del falò è al massimo!",
    msg_added_fuel: "Aggiunto combustibile! ({type}: +{amount}s)",
    msg_lit_fire_spark: "Hai fatto scattare le scintille con le pietre e acceso il fuoco con le foglie!",
    msg_no_fuel: "Nessun combustibile nell'inventario! (Serve Paglia, Legnetti o Legna)",
    msg_no_ignition: "Servono almeno 2 Pietre and 1 Foglia per fare la scintilla e accendere!",
    msg_world_edge: "Hai raggiunto il confine del mondo!",
    interact_harvest_log: "PREMI E PER RACCOGLIERE IL TRONCO CADUTO",
    interact_harvest_liana: "PREMI E PER RACCOGLIERE LA LIANA",
    msg_collected_log: "+1 Legno (Tronco caduto)",
    msg_collected_liana: "+1 Corda (Liana)",
    msg_need_mats_raft: "Asso. Zattera (Servono 4 Tronchi, 2 Liane, 2 Bastoni)",
    msg_press_construct: "Premi E per costruire la zattera",
    msg_press_sail: "Premi E per navigare",
    msg_press_disembark: "Premi E per sbarcare",
    msg_raft_repaired: "Zattera costruita! Pronta per navigare.",
    msg_extreme_heat: "🌡️ CALORE ESTREMO: L'idratazione scende più velocemente!",
    msg_in_lava: "🔥 NELLA LAVA! STAI SUBENDO DANNI! 🔥",
    obj_sail_explore: "Naviga ed esplora le altre isole",
    inv_slot_head: "TESTA",
    inv_slot_torso: "BUSTO",
    inv_slot_legs: "GAMBE",
    inv_slot_feet: "PIEDI",
    inv_slot_right_hand: "MANO DESTRA",
    inv_slot_left_hand: "MANO SINISTRA",
    "inv.fishing_rod": "Canna da Pesca",
    "recipe.fishing_rod": "2 Bastoni, 2 Corde",
    "inv.egg": "Uovo",
    "inv.cooked_egg": "Uovo Sodo",
    interact_harvest_egg: "PREMI E PER RACCOGLIERE L'UOVO",
    interact_harvest_cooked_egg: "PREMI E PER RACCOGLIERE L'UOVO SODO",
    interact_feed_hen: "PREMI E PER NUTRIRE ROSITA (1 Verme)",
    msg_hen_laid_egg: "Rosita ha deposto un uovo!",
    msg_collected_egg: "+1 Uovo",
    msg_collected_cooked_egg: "+1 Uovo Sodo",
    msg_cooked_egg: "Uovo Cotto!",
    msg_ate_cooked_egg: "Mangiato uovo sodo! +15 HP, +30 Energia, +5 Idratazione",
    msg_fishing_wait: "Pesca in corso... attendi che abbocchi!",
    msg_fishing_bite: "UN PESCE HA ABBOCCATO! CLICCA PER TIRARE!",
    msg_fishing_caught: "Pesce pescato!",
    msg_fishing_escaped: "Il pesce è fuggito!",
    msg_fishing_early: "Hai tirato troppo presto!",
    msg_fishing_cancelled: "Pesca annullata!",
    msg_no_bait: "Serve 1 Verme come esca! Raccoglili dal gabbiano morto.",
    "inv.torch": "Torcia a Mano",
    "recipe.torch": "1 Bastone, 2 Foglie",
    "inv.berries": "Bacche Selvatiche",
    interact_harvest_berries: "PREMI E PER RACCOGLIERE LE BACCHE",
    msg_collected_berries: "+3 Bacche Selvatiche",
    msg_ate_berries: "Mangiate bacche selvatiche! +5 HP, +15 Energia, +10 Idratazione"
  },
};

export let currentLang = 'en';

export function getTranslation(key, variables = {}) {
  const langDict = translations[currentLang] || translations['en'];
  
  // 1. Try direct lookup (in case of flat keys with dots like "inv.explorer_vest")
  let text = langDict[key];
  
  // 2. Try nested dot traversal if direct lookup failed
  if (text === undefined && key.includes('.')) {
    text = key.split('.').reduce((obj, property) => {
      return obj && obj[property];
    }, langDict);
  }
  
  // 3. Fallback to English dictionary
  if (text === undefined) {
    text = translations['en'][key];
    if (text === undefined && key.includes('.')) {
      text = key.split('.').reduce((obj, property) => {
        return obj && obj[property];
      }, translations['en']);
    }
  }
  
  // 4. Ultimate fallback to key itself
  if (text === undefined) text = key;
  
  // Replace variables like {val}
  Object.keys(variables).forEach(varName => {
    text = text.replace(`{${varName}}`, variables[varName]);
  });
  
  return text;
}

export function setLanguage(langCode) {
  if (!translations[langCode]) return;
  currentLang = langCode;
  localStorage.setItem('game_language', langCode);
  
  // 1. Update all static HTML elements marked with data-translate
  const elements = document.querySelectorAll('[data-translate]');
  elements.forEach(el => {
    const key = el.getAttribute('data-translate');
    el.textContent = getTranslation(key);
  });
  
  // 2. Update interaction prompt if it exists
  const prompt = document.getElementById('interaction-prompt');
  if (prompt) {
    // If player is looking at the board, we update dynamically elsewhere, but this is the baseline
    prompt.innerHTML = getTranslation('interact_harvest');
  }

  // 3. Update active Hotbar Labels
  const slotLabels = {
    0: 'spear',
    1: 'axe',
    2: 'water',
    3: 'leaves',
    4: 'rope',
    5: 'wood',
    6: 'pickaxe',
    7: 'stone'
  };

  // If gold ore is harvested, slot 7 might change name
  const slot8 = document.querySelector('.hotbar-slot[data-slot="7"]');
  let hasOre = false;
  if (slot8) {
    const icon = slot8.querySelector('.slot-icon');
    if (icon && icon.textContent === "🪙") {
      hasOre = true;
    }
  }

  document.querySelectorAll('.hotbar-slot').forEach(slot => {
    const idx = parseInt(slot.getAttribute('data-slot'));
    const labelSpan = slot.querySelector('.slot-label');
    if (labelSpan) {
      if (idx === 7 && hasOre) {
        labelSpan.textContent = getTranslation('hotbar.ore');
      } else {
        const langKey = slotLabels[idx];
        if (langKey) {
          labelSpan.textContent = getTranslation(`hotbar.${langKey}`);
        }
      }
    }
  });

  // 4. Update dynamic Objective Text
  const objTextEl = document.getElementById('objective-text');
  if (objTextEl) {
    const slot8CountEl = document.querySelector('.hotbar-slot[data-slot="7"] .slot-count');
    let oreCount = 0;
    if (slot8CountEl) {
      const match = slot8CountEl.textContent.match(/\d+/);
      if (match && hasOre) oreCount = parseInt(match[0]);
    }
    
    if (oreCount >= 5 || objTextEl.textContent.toLowerCase().includes('complete') || objTextEl.textContent.includes('達成') || objTextEl.textContent.includes('completado') || objTextEl.textContent.includes('atteint') || objTextEl.textContent.includes('erreicht') || objTextEl.textContent.includes('concluído') || objTextEl.textContent.includes('completato')) {
      objTextEl.textContent = getTranslation('obj_complete');
      objTextEl.style.color = "#00ff88";
    } else {
      objTextEl.textContent = getTranslation('obj_progress', { val: oreCount });
      objTextEl.style.color = "#ffd700";
    }
  }

  // Update feedback board placeholder and buttons if active
  const boardPlaceholderEl = document.getElementById('feedback-input');
  if (boardPlaceholderEl) {
    boardPlaceholderEl.placeholder = getTranslation('board_placeholder');
  }
  const boardSubmitEl = document.getElementById('feedback-submit');
  if (boardSubmitEl) {
    boardSubmitEl.textContent = getTranslation('board_submit');
  }
  const boardCloseEl = document.getElementById('feedback-close');
  if (boardCloseEl) {
    boardCloseEl.textContent = getTranslation('board_close');
  }

  // Dispatch an event
  window.dispatchEvent(new CustomEvent('languagechanged', { detail: langCode }));
}

// Load default saved language if present
const savedLang = localStorage.getItem('game_language');
if (savedLang && translations[savedLang]) {
  currentLang = savedLang;
}
