// Localization Dictionary
export const translations = {
  en: {
    game_subtitle: "SUNSET SURVIVAL & MINING",
    game_desc: "Explore a low-poly tropical island, mine underground tunnels in search of gold, and avoid drowning in the open ocean. Dig through rocks using your pickaxe and repair the boat.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "PLEASE ROTATE DEVICE",
    rotate_warning_desc: "This game is designed to be played in landscape mode (horizontal) only.",
    start_btn: "START ENGINE",
    continue_btn: "🔄 CONTINUE",
    controls_title: "CONTROL TELEMETRY",
    ctrl_mv: "FPS Movement",
    ctrl_look: "Look Around",
    ctrl_dig: "Dig / Attack",
    ctrl_jump: "Jump / Swim Up",
    ctrl_harvest: "Harvest Ore / Resource",
    ctrl_switch: "Switch Tool",
    hud_objective: "OBJECTIVE",
    hud_compass: "COMPASS",
    hud_distance: "DISTANCE",
    hud_health: "HEALTH",
    hud_energy: "ENERGY",
    hud_hydration: "HYDRATION",
    obj_initial: "Collect ore for boat repairs",
    obj_progress: "Collect ore for boat repairs ({val}/5)",
    obj_complete: "Objective Completed! Boat repaired.",
    interact_harvest: "PRESS E TO HARVEST ORE",
    interact_board: "PRESS E TO READ FEEDBACK BOARD",
    board_title: "COMMUNITY FEEDBACK TERMINAL",
    board_placeholder: "Enter your message here...",
    board_submit: "TRANSMIT",
    board_close: "CLOSE",
    msg_mined: "Mined Gold Ore! Pick it up.",
    msg_depleted: "Ore Deposit Depleted!",
    msg_collected: "+1 Gold Ore",
    msg_goal_complete: "Survival Goal Complete!",
    interact_harvest_wood: "PRESS E TO HARVEST WOOD",
    msg_chopped: "Chop!",
    msg_tree_felled: "Tree felled!",
    msg_collected_wood: "+1 Wood",
    hotbar: {
      spear: "Spear",
      axe: "Axe",
      water: "Water",
      leaves: "Leaves",
      rope: "Rope",
      wood: "Wood",
      pickaxe: "Pickaxe",
      stone: "Stone",
      ore: "Ore"
    },
    confirm_title: "QUIT GAME?",
    confirm_desc: "Are you sure you want to return to the main menu? Your progress will be lost.",
    confirm_yes: "YES, EXIT",
    confirm_no: "NO, CONTINUE",
    inv_title: "INVENTORY",
    inv_my_bag: "MY BAG",
    inv_crafting: "CRAFTING STATION",
    inv_character: "CHARACTER",
    inv_stat_energy: "Stamina Decay",
    inv_stat_hydration: "Hydration Decay",
    inv_stat_speed: "Speed Bonus",
    "inv.straw_hat": "Straw Hat",
    "inv.explorer_vest": "Explorer Vest",
    "inv.grass_pants": "Grass Pants",
    "inv.wooden_boots": "Wooden Boots",
    "inv.empty": "[Empty]",
    "recipe.rope": "3 Leaves",
    "recipe.straw_hat": "6 Leaves, 2 Ropes",
    "recipe.grass_pants": "8 Leaves, 3 Ropes",
    "recipe.wooden_boots": "4 Wood, 2 Ropes",
    "inv.foundation": "Wood Foundation",
    "inv.wall": "Wood Wall",
    "inv.primitive_roof": "Leaf Roof",
    "inv.wood_roof": "Wood Roof",
    "inv.door": "Wood Door",
    "inv.worn_map": "Worn Map",
    "inv.charcoal": "Charcoal",
    "recipe.foundation": "4 Planks, 2 Wood",
    "recipe.wall": "3 Planks, 4 Sticks",
    "recipe.primitive_roof": "4 Leaves, 2 Ropes",
    "recipe.wood_roof": "3 Planks, 2 Wood",
    "recipe.door": "2 Planks, 2 Ropes",
    "recipe.worn_map": "4 Leaves, 1 Charcoal",
    "inv.planted_bush": "Planted Berry Bush",
    "recipe.planted_bush": "3 Berries",
    "inv.planted_cane": "Planted Bamboo Cane",
    "recipe.planted_cane": "2 Cane, 1 Rope",
    "inv.raw_fish": "Raw Fish",
    "inv.worm": "Worm",
    "inv.raw_crab": "Raw Crab",
    "inv.cooked_meat": "Cooked Meat",
    "inv.campfire": "Campfire",
    "recipe.campfire": "4 Wood, 2 Stone",
    interact_cook: "PRESS E TO COOK MEAT",
    interact_harvest_crab: "PRESS E TO HARVEST RAW CRAB",
    interact_harvest_fish: "PRESS E TO HARVEST RAW FISH",
    interact_harvest_cooked: "PRESS E TO HARVEST COOKED MEAT",
    interact_harvest_worm: "PRESS E TO COLLECT WORM",
    msg_hunted_crab: "Hunted Crab!",
    msg_hunted_fish: "Hunted Fish!",
    msg_collected_worm: "+1 Worm",
    msg_cooked_crab: "Cooked Crab Meat!",
    msg_cooked_fish: "Cooked Fish Meat!",
    msg_placed_campfire: "Placed Campfire!",
    msg_ate_cooked: "Ate cooked meat! +20 HP, +40 Energy",
    msg_ate_raw: "Ate raw food! Drained 5 HP, 10 Energy",
    msg_collected_raw_crab: "+1 Raw Crab",
    msg_collected_raw_fish: "+1 Raw Fish",
    msg_collected_cooked: "+1 Cooked Meat",
    "inv.stick": "Stick",
    "inv.cane": "Cane",
    interact_harvest_stick: "PRESS E TO COLLECT STICK",
    interact_harvest_cane: "PRESS E TO COLLECT CANE",
    msg_cane_hit: "Hit cane!",
    msg_cane_broken: "Cane broken!",
    msg_collected_stick: "+1 Stick",
    msg_collected_cane: "+1 Cane",
    msg_already_hydrated: "Already hydrated!",
    msg_drank_water: "Drank water! +30 Hydration",
    interact_cook_fuel: "PRESS E TO COOK MEAT / PRESS F TO ADD FUEL (Fuel: {fuel}s)",
    interact_fuel_only: "PRESS F TO ADD FUEL (Fuel: {fuel}s)",
    interact_relight: "PRESS F TO LIGHT FIRE (2 Stones & 1 Leaf)",
    msg_fire_out: "FIRE IS OUT (Needs 2 Stones & 1 Leaf)",
    msg_fire_is_out: "The fire is out! Add fuel/stones to light it.",
    msg_fire_full: "Campfire fuel capacity is full!",
    msg_added_fuel: "Added fuel! ({type}: +{amount}s)",
    msg_lit_fire_spark: "Sparked the stones and lit the fire with leaves!",
    msg_no_fuel: "No fuel in inventory! (Need Leaves, Sticks, or Wood)",
    msg_no_ignition: "Need 2 Stones and 1 Leaf to spark the fire!",
    msg_world_edge: "Reached the edge of the world!",
    interact_harvest_log: "PRESS E TO COLLECT FALLEN LOG",
    interact_harvest_liana: "PRESS E TO COLLECT LIANA",
    msg_collected_log: "+1 Wood (Fallen Log)",
    msg_collected_liana: "+1 Rope (Liana)",
    msg_need_mats_raft: "Construct Raft (Need 4 Logs, 2 Lianas, 2 Sticks)",
    msg_press_construct: "Press E to Construct Raft",
    msg_press_sail: "Press E to Sail Raft",
    msg_press_disembark: "Press E to Disembark",
    msg_raft_repaired: "Raft Constructed! Ready to sail.",
    msg_extreme_heat: "🌡️ EXTREME HEAT: Hydration draining faster!",
    msg_in_lava: "🔥 IN LAVA! TAKING DAMAGE! 🔥",
    msg_player_died: "⚠️ YOU DIED! RESPAWNED AT THE BEACH.",
    obj_sail_explore: "Sail and explore other islands",
    inv_slot_head: "HEAD",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "LEGS",
    inv_slot_feet: "FEET",
    inv_slot_right_hand: "RIGHT HAND",
    inv_slot_left_hand: "LEFT HAND",
    "inv.fishing_rod": "Fishing Rod",
    "recipe.fishing_rod": "2 Sticks, 2 Ropes",
    "inv.sharp_stone": "Sharp Stone",
    "inv.plank": "Plank",
    "inv.stone_block": "Stone Block",
    "inv.primitive_spear": "Bamboo Spear",
    "inv.primitive_axe": "Primitive Axe",
    "inv.primitive_pickaxe": "Primitive Pickaxe",
    "inv.refined_spear": "Refined Spear",
    "inv.refined_axe": "Refined Axe",
    "inv.refined_pickaxe": "Refined Pickaxe",
    "inv.workbench": "Workbench",
    "inv.furnace": "Smelting Furnace",
    "inv.lab_table": "Lab Table",
    "inv.raw_silicon": "Raw Silicon",
    "inv.raw_copper": "Raw Copper",
    "inv.raw_titanium": "Raw Titanium",
    "inv.copper_ingot": "Copper Ingot",
    "inv.titanium_plate": "Titanium Plate",
    interact_smelt: "PRESS E TO SMELT ORES",
    "inv.egg": "Egg",
    "inv.cooked_egg": "Cooked Egg",
    interact_harvest_egg: "PRESS E TO COLLECT EGG",
    interact_harvest_cooked_egg: "PRESS E TO COLLECT COOKED EGG",
    interact_feed_hen: "PRESS E TO FEED ROSITA (1 Worm)",
    msg_hen_laid_egg: "Rosita laid an egg!",
    msg_collected_egg: "+1 Egg",
    msg_collected_cooked_egg: "+1 Cooked Egg",
    msg_cooked_egg: "Cooked Egg!",
    msg_ate_cooked_egg: "Ate cooked egg! +15 HP, +30 Energy, +5 Hydration",
    msg_fishing_wait: "Fishing... wait for a bite!",
    msg_fishing_bite: "A FISH IS BITING! CLICK TO REEL IN!",
    msg_fishing_caught: "Caught a fish!",
    msg_fishing_escaped: "The fish got away!",
    msg_fishing_early: "Reeled in too early!",
    msg_fishing_cancelled: "Fishing cancelled!",
    msg_no_bait: "Needs 1 Worm as bait! Collect them from the dead seagull.",
    "inv.torch": "Hand Torch",
    "recipe.torch": "1 Stick, 2 Leaves",
    "inv.berries": "Wild Berries",
    "inv.spectrometer": "Spectrometer",
    "recipe.spectrometer": "2 Copper, 1 Glass",
    "inv.chemical_analyzer": "Chemical Analyzer",
    "recipe.chemical_analyzer": "1 Spectrometer, 2 Ropes",
    "inv.heat_suit": "Heat Suit",
    "recipe.heat_suit": "3 Titanium, 1 Explorer Vest",
    "inv.silicon": "Silicon",
    "inv.titanium": "Titanium",
    "inv.copper": "Copper",
    "inv.glass": "Glass",
    "recipe.glass": "2 Silicon",
    interact_scan: "PRESS E TO ANALYZE ELEMENTAL COMPOSITION",
    msg_scanned: "Analyzed block composition!",
    interact_harvest_berries: "PRESS E TO GATHER BERRIES",
    msg_collected_berries: "+3 Wild Berries",
    msg_ate_berries: "Ate wild berries! +5 HP, +15 Energy, +10 Hydration",
    
    // Game Guide Strings
    guide_btn: "📖 GAME GUIDE & INFO",
    guide_title: "ARCHIPELAGO SURVIVAL MANUAL",
    guide_download_pdf: "⬇️ DOWNLOAD PDF",
    guide_close: "CLOSE",
    tab_survival: "❤️ SURVIVAL & HUD",
    tab_movement: "🏃 MOVEMENT & EXPLO",
    tab_mining: "⛏️ DIGGING & TERRAIN",
    tab_crafting: "🛠️ CRAFT & BUILD",
    tab_weather: "🌦️ WEATHER & FAUNA",
    guide_quicklink: "Press 📖 GUIDE for the full gameplay and controls manual.",
    guide_h_survival: "Survival Indicators",
    guide_p_survival: "Survival on this island requires managing three critical bars visible at the bottom-left of the screen:",
    guide_lbl_health: "Health:",
    guide_desc_health: "Decreases when you drown, starve, freeze or consume raw food. Eating cooked meat restores it.",
    guide_lbl_energy: "Energy:",
    guide_desc_energy: "Drains by running, jumping, and swinging tools. It regenerates slowly when walking or standing still.",
    guide_lbl_hydration: "Hydration:",
    guide_desc_hydration: "Decays over time. You must drink fresh water from the inland lake to restore it. Drinking salty sea water causes damage!",
    guide_tip_title: "SURVIVAL TIP:",
    guide_tip_survival: "Always craft clothes. A straw hat or wooden boots significantly reduce hydration and energy decay!",
    guide_h_movement: "Controls & Locomotion",
    guide_p_movement: "Master the movement controls to explore the large volcanic island and navigate back to the sea:",
    guide_lbl_keys: "Movement:",
    guide_desc_keys: "Use WASD or Arrow keys to walk around.",
    guide_lbl_sprint: "Sprinting:",
    guide_desc_sprint: "Hold the Shift key to run faster, but keep an eye on your Energy bar!",
    guide_lbl_swimming: "Swimming & Diving:",
    guide_desc_swimming: "Wade into water to swim automatically. Hold Space to swim up. Dive under to explore seabed corals!",
    guide_lbl_raft: "Raft Navigation:",
    guide_desc_raft: "Repair the boat to unlock ocean travel. You can steer rafts to explore other islands on the horizon.",
    guide_h_mining: "Terraforming & Ore Extraction",
    guide_p_mining: "The environment is fully destructible. Use your tools to shape the island or dig deep into the earth:",
    guide_lbl_digging: "Digging:",
    guide_desc_digging: "Equip the Pickaxe (Slot 7) and Left Click on any voxel to excavate caves or carve tunnels.",
    guide_lbl_sculpting: "Sculpting:",
    guide_desc_sculpting: "Collect Sand or Stone blocks, select them in your hotbar, and place them to build bridges or repair holes.",
    guide_lbl_gold: "Mining Gold Ore:",
    guide_desc_gold: "Hit the glittering gold ore rocks with your Pickaxe to break them. Pick up the chunks to repair the boat!",
    guide_tip_mining: "Digging underground triggers transitions through layers. You will find light soil, clay, and granite deep down.",
    guide_h_crafting: "Crafting Station & Construction",
    guide_p_crafting: "Gather materials to craft tools, gear, survival structures, or bases:",
    guide_lbl_inventory: "Open Inventory:",
    guide_desc_inventory: "Press Tab or click the Backpack icon to view inventory and the Crafting Panel.",
    guide_lbl_recipes: "Basic Recipes:",
    guide_desc_recipes: "Craft Ropes from Leaves, Straw Hats for sun protection, and Campfires to cook raw food.",
    guide_lbl_building: "Base Building:",
    guide_desc_building: "Craft foundations, walls, doors, and roofs, and place them on the island to build customized shelters!",
    guide_h_weather: "Atmosphere, Seasons & Wildlife",
    guide_p_weather: "The island is a living ecosystem with changing weather conditions, seasons, and local wildlife:",
    guide_lbl_weather: "Dynamic Weather:",
    guide_desc_weather: "Experience rain, snow, heavy clouds, and tropical storms. Storms cause leaf roofs to slowly decay!",
    guide_lbl_seasons: "Seasons:",
    guide_desc_seasons: "Seasons affect temperature and weather. In Winter, the freshwater lake freezes completely, allowing you to walk on ice.",
    guide_lbl_hunting: "Hunting & Cooking:",
    guide_desc_hunting: "Hunt beach crabs or shallow-water fish using your Spear (Slot 1). Ignite campfires using wood to cook meat!",
    guide_lbl_fishing: "Fishing:",
    guide_desc_fishing: "Equip the Fishing Rod (Slot 6). Stand near deep water, look at the water, and Left Click to cast. Click again when you see a splash to catch fish.",
    guide_lbl_smelting: "Smelting:",
    guide_desc_smelting: "Build a Furnace. Insert wood or coal as fuel, along with raw ores (Copper, Silicon, Titanium) to smelt ingots and glass.",
    guide_lbl_farming: "Farming:",
    guide_desc_farming: "Craft a Planted Berry Bush using 3 Berries and place it. It will grow harvestable berries every 60 seconds.",
    guide_lbl_canes: "Planting Canes:",
    guide_desc_canes: "Craft a Planted Bamboo Cane using 2 Cane and 1 Rope, and place it. Hit it with your Spear or Axe to harvest cane.",
  },
  ja: {
    game_subtitle: "夕暮れの生存と採掘",
    game_desc: "ローポリの熱帯の島を探索し、金を求めて地下トンネルを採掘し、開けた海でおぼれないようにしてください。ピッケルで岩を掘り進み、ボートを修理しましょう。",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "画面を横にしてください",
    rotate_warning_desc: "このゲームは横画面（ランドスケープ）専用です。",
    start_btn: "エンジン始動",
    continue_btn: "🔄 再開",
    controls_title: "操作テレメトリー",
    ctrl_mv: "FPS移動",
    ctrl_look: "周囲を見回す",
    ctrl_dig: "掘る / 攻撃",
    ctrl_jump: "ジャンプ / 浮上する",
    ctrl_harvest: "鉱石・資源 of 回収",
    ctrl_switch: "ツールの切り替え",
    hud_objective: "目標",
    hud_compass: "コンパス",
    hud_distance: "距離",
    hud_health: "体力",
    hud_energy: "スタミナ",
    hud_hydration: "水分",
    obj_initial: "ボート修理用の鉱石を収集する",
    obj_progress: "ボート修理用の鉱石を収集する ({val}/5)",
    obj_complete: "目標達成！ボートが修理されました。",
    interact_harvest: "Eキーで鉱石を回収",
    interact_board: "Eキーで掲示板を読む",
    board_title: "コミュニティ・フィードバック・ターミナル",
    board_placeholder: "メッセージを入力してください...",
    board_submit: "送信する",
    board_close: "閉じる",
    msg_mined: "金鉱石を採掘しました！拾ってください。",
    msg_depleted: "鉱床が枯渇しました！",
    msg_collected: "+1 金鉱石",
    msg_goal_complete: "サバイバルゴール達成！",
    interact_harvest_wood: "Eキーで木材を回収",
    msg_chopped: "チョップ！",
    msg_tree_felled: "木が倒れました！",
    msg_collected_wood: "+1 木材",
    hotbar: {
      spear: "槍",
      axe: "斧",
      water: "水",
      leaves: "葉",
      rope: "ロープ",
      wood: "木",
      pickaxe: "ツルハシ",
      stone: "石",
      ore: "鉱石"
    },
    confirm_title: "終了しますか？",
    confirm_desc: "メインメニューに戻りますか？進行状況は失われます。",
    confirm_yes: "はい、終了します",
    confirm_no: "いいえ、続けます",
    inv_title: "インベントリ",
    inv_my_bag: "バッグ",
    inv_crafting: "クラフトステーション",
    inv_character: "キャラクター",
    inv_stat_energy: "スタミナ消費",
    inv_stat_hydration: "水分消費",
    inv_stat_speed: "速度ボーナス",
    "inv.straw_hat": "麦わら帽子",
    "inv.explorer_vest": "探検家のベスト",
    "inv.grass_pants": "草のズボン",
    "inv.wooden_boots": "木製のブーツ",
    "inv.empty": "[空]",
    "recipe.rope": "葉 x3",
    "inv.planted_bush": "ベリーの低木",
    "recipe.planted_bush": "ベリー x3",
    "inv.planted_cane": "植えられた竹",
    "recipe.planted_cane": "竹 x2, ロープ x1",
    "recipe.straw_hat": "葉 x6, ロープ x2",
    "recipe.grass_pants": "葉 x8, ロープ x3",
    "recipe.wooden_boots": "木材 x4, ロープ x2",
    inv_slot_head: "頭部",
    inv_slot_torso: "胸部",
    inv_slot_legs: "脚部",
    inv_slot_feet: "足部",
    inv_slot_right_hand: "右手",
    inv_slot_left_hand: "左手",
    
    // Game Guide Strings
    guide_btn: "📖 ゲームガイド",
    guide_title: "アキペラゴ生存マニュアル",
    guide_download_pdf: "⬇️ PDFをダウンロード",
    guide_close: "閉じる",
    tab_survival: "❤️ 生存 & HUD",
    tab_movement: "🏃 移動 & 探索",
    tab_mining: "⛏️ 採掘 & 地形",
    tab_crafting: "🛠️ クラフト & 建設",
    tab_weather: "🌦️ 天候 & 生物",
    guide_quicklink: "操作方法とゲームマニュアルを表示するには、📖 ガイド を押してください。",
    guide_h_survival: "サバイバルインジケーター",
    guide_p_survival: "島で生き残るには、画面の左下に表示される3つの重要なゲージを管理する必要があります：",
    guide_lbl_health: "体力 (Health):",
    guide_desc_health: "溺水、飢え、凍え、または生の食品を食べることで減少します。調理された肉を食べることで回復します。",
    guide_lbl_energy: "スタミナ (Energy):",
    guide_desc_energy: "走る、跳ぶ、道具を振ることで消費されます。歩くか立ち止まることで徐々に回復します。",
    guide_lbl_hydration: "水分 (Hydration):",
    guide_desc_hydration: "時間の経過とともに減少します。中央の湖の淡水を飲んで回復してください。海水を飲むとダメージを受けます！",
    guide_tip_title: "サバイバルのヒント:",
    guide_tip_survival: "常に衣服をクラフトしてください。麦わら帽子や木のブーツは、水分とスタミナの消費を大幅に抑えます！",
    guide_h_movement: "操作と移動",
    guide_p_movement: "火山島を探索し、海を渡るための基本的な移動方法：",
    guide_lbl_keys: "移動:",
    guide_desc_keys: "WASDまたは矢印キーを使用して歩き回ります。",
    guide_lbl_sprint: "ダッシュ:",
    guide_desc_sprint: "Shiftキーを押し続けると速く走ることができますが、スタミナゲージに注意してください！",
    guide_lbl_swimming: "水泳と潜水:",
    guide_desc_swimming: "水に入ると自動的に泳ぎます。スペースキーを長押しすると浮上します。潜ってサンゴ礁を探索しましょう！",
    guide_lbl_raft: "イカダの操縦:",
    guide_desc_raft: "初期のボートを修理して海への探索をアンロックします。イカダを作成して地平線に見える別の島を探索できます。",
    guide_h_mining: "地形成形と鉱石採掘",
    guide_p_mining: "環境は完全に破壊可能です。道具を使って島を成形したり、地下深くを掘り進めたりできます：",
    guide_lbl_digging: "穴掘り:",
    guide_desc_digging: "ツルハシ（スロット7）を装備し、左クリックでボクセルブロックを掘って洞窟やトンネルを作ります。",
    guide_lbl_sculpting: "ブロック設置:",
    guide_desc_sculpting: "ホットバーで砂や石のブロックを選択し、左クリックで設置して橋を作ったり穴を塞いだりします。",
    guide_lbl_gold: "金鉱石の採掘:",
    guide_desc_gold: "きらめく金鉱脈をツルハシで叩いて鉱石を収集し、ボートを修理してください。",
    guide_tip_mining: "地下を掘り進めると、軽い土、粘土、硬い花崗岩など、さまざまな地層を通過します。",
    guide_h_crafting: "クラフトステーションと拠点建設",
    guide_p_crafting: "素材を集めてサバイバル道具をクラフトし、シェルターを建築します：",
    guide_lbl_inventory: "インベントリを開く:",
    guide_desc_inventory: "Tabキーを押すか、バックパックアイコンをクリックして、右側のクラフトパネルを表示します。",
    guide_lbl_recipes: "基本レシピ:",
    guide_desc_recipes: "葉っぱからロープを、日よけ用の麦わら帽子を、調理用の焚き火を作成できます。",
    guide_lbl_building: "拠点建築:",
    guide_desc_building: "木製の土台、壁、ドア、葉っぱの屋根をクラフトして設置し、自分だけの避難所を建設しましょう！",
    guide_h_weather: "天候、四季と野生生物",
    guide_p_weather: "島は変化する天候、季節、野生動物が存在するエコシステムです：",
    guide_lbl_weather: "ダイナミックな天候:",
    guide_desc_weather: "雨、雪、熱帯の嵐を体験します。嵐は葉っぱの屋根をゆっくりと劣化させます！",
    guide_lbl_seasons: "季節の移り変わり:",
    guide_desc_seasons: "季節は天候に影響します。冬の間、山頂の淡水湖は完全に凍りつき、氷の上を歩くことができます！",
    guide_lbl_hunting: "狩猟と料理:",
    guide_desc_hunting: "槍（スロット1）を使ってカニや魚を狩ります。木材で焚き火を起こして肉を調理しましょう！",
    guide_lbl_fishing: "釣り:",
    guide_desc_fishing: "釣り竿（スロット6）を装備します。深い水の近くに立ち、水面を見つめて左クリックでキャストします。水しぶきが上がったらもう一度クリックして魚を釣り上げます。",
    guide_lbl_smelting: "製錬:",
    guide_desc_smelting: "製錬炉を建設します。木材や石炭を燃料として入れ、銅、シリコン、チタンなどの鉱石を溶かしてインゴットやガラスを作成します。",
    guide_lbl_farming: "農業:",
    guide_desc_farming: "ベリー3個でベリーの低木を作成し、地面に配置します。60秒ごとに収穫可能なベリーが成長します。",
    guide_lbl_canes: "竹の植林:",
    guide_desc_canes: "竹2本とロープ1本で植えられた竹を作成し、配置します。槍や斧で叩いて竹の資源を回収できます。",
  },
  es: {
    game_subtitle: "SUPERVIVENCIA Y MINERÍA AL ATARDECER",
    game_desc: "Explora una isla tropical low-poly, cava túneles subterráneos en busca de oro y evita ahogarte en el océano abierto. Hazte camino entre las rocas usando tu pico y repara el barco.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "POR FAVOR ROTAR DISPOSITIVO",
    rotate_warning_desc: "Este juego está diseñado para jugarse únicamente en modo horizontal.",
    start_btn: "ARRANCAR MOTOR",
    continue_btn: "🔄 CONTINUAR",
    controls_title: "TELEMETRÍA DE CONTROL",
    ctrl_mv: "Movimiento FPS",
    ctrl_look: "Mirar alrededor",
    ctrl_dig: "Cavar / Atacar",
    ctrl_jump: "Saltar / Nadar arriba",
    ctrl_harvest: "Recoger oro / recursos",
    ctrl_switch: "Cambiar herramienta",
    hud_objective: "OBJETIVO",
    hud_compass: "BRÚJULA",
    hud_distance: "DISTANCIA",
    hud_health: "SALUD",
    hud_energy: "ENERGÍA",
    hud_hydration: "HIDRATACIÓN",
    obj_initial: "Recoge mineral para reparar el barco",
    obj_progress: "Recoge mineral para reparar el barco ({val}/5)",
    obj_complete: "¡Objetivo completado! Barco reparado.",
    interact_harvest: "PULSA E PARA RECOGER MINERAL",
    interact_board: "PULSA E PARA LEER EL TABLÓN",
    board_title: "TERMINAL DE FEEDBACK DE LA COMUNIDAD",
    board_placeholder: "Escribe tu mensaje aquí...",
    board_submit: "TRANSMITIR",
    board_close: "CERRAR",
    msg_mined: "¡Mineral de oro extraído! Recógelo.",
    msg_depleted: "¡Yacimiento de mineral agotado!",
    msg_collected: "+1 Mineral de oro",
    msg_goal_complete: "¡Meta de supervivencia completada!",
    interact_harvest_wood: "PRESIONA E PARA RECOLECTAR MADERA",
    msg_chopped: "¡Tajo!",
    msg_tree_felled: "¡Árbol talado!",
    msg_collected_wood: "+1 Madera",
    hotbar: {
      spear: "Lanza",
      axe: "Hacha",
      water: "Agua",
      leaves: "Hojas",
      rope: "Cuerda",
      wood: "Madera",
      pickaxe: "Pico",
      stone: "Piedra",
      ore: "Mineral"
    },
    confirm_title: "¿ABANDONAR PARTIDA?",
    confirm_desc: "¿Seguro que quieres volver al menú principal? Se perderá tu progreso.",
    confirm_yes: "SÍ, SALIR",
    confirm_no: "NO, CONTINUAR",
    inv_title: "INVENTARIO",
    inv_my_bag: "MI BOLSA",
    inv_crafting: "ESTACIÓN DE ARTESANÍA",
    inv_character: "PERSONAJE",
    inv_stat_energy: "Consumo de Energía",
    inv_stat_hydration: "Consumo de Hidratación",
    inv_stat_speed: "Bono de Velocidad",
    "inv.straw_hat": "Sombrero de Paja",
    "inv.explorer_vest": "Chaleco de Explorador",
    "inv.grass_pants": "Pantalones de Hierba",
    "inv.wooden_boots": "Botas de Madera",
    "inv.empty": "[Vacío]",
    "recipe.rope": "3 Hojas",
    "inv.planted_bush": "Arbusto de Bayas Plantado",
    "recipe.planted_bush": "3 Bayas",
    "inv.planted_cane": "Caña de Bambú Plantada",
    "recipe.planted_cane": "2 Cañas, 1 Cuerda",
    "recipe.straw_hat": "6 Hojas, 2 Cuerdas",
    "recipe.grass_pants": "8 Hojas, 3 Cuerdas",
    "recipe.wooden_boots": "4 Madera, 2 Cuerdas",
    inv_slot_head: "CABEZA",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "PIERNAS",
    inv_slot_feet: "PIES",
    inv_slot_right_hand: "MANO DERECHA",
    inv_slot_left_hand: "MANO IZQUIERDA",
    
    // Game Guide Strings
    guide_btn: "📖 GUÍA DEL JUEGO",
    guide_title: "MANUAL DE SUPERVIVENCIA - ARCHIPELAGO",
    guide_download_pdf: "⬇️ DESCARGAR PDF",
    guide_close: "CERRAR",
    tab_survival: "❤️ SUPERVIVENCIA & HUD",
    tab_movement: "🏃 MOVIMIENTO & EXPLORACIÓN",
    tab_mining: "⛏️ EXCAVACIÓN & TERRENO",
    tab_crafting: "🛠️ CREACIÓN & CONSTRUCCIÓN",
    tab_weather: "🌦️ CLIMA & FAUNA",
    guide_quicklink: "Presiona 📖 GUÍA para ver el manual completo de juego y controles.",
    guide_h_survival: "Indicadores de Supervivencia",
    guide_p_survival: "La supervivencia en esta isla requiere gestionar tres barras vitales visibles en la parte inferior izquierda:",
    guide_lbl_health: "Salud:",
    guide_desc_health: "Disminuye al ahogarse, pasar hambre, congelarse o comer comida cruda. Comer carne cocinada la restaura.",
    guide_lbl_energy: "Energía:",
    guide_desc_energy: "Se agota al correr, saltar y usar herramientas. Se regenera lentamente al caminar o quedarse quieto.",
    guide_lbl_hydration: "Hidratación:",
    guide_desc_hydration: "Disminuye con el tiempo. Bebe agua dulce del lago central para recuperarla. ¡Beber agua salada causa daño!",
    guide_tip_title: "CONSEJO DE SUPERVIVENCIA:",
    guide_tip_survival: "Fabrica ropa siempre. ¡Un sombrero de paja o botas de madera reducen mucho el consumo de energía e hidratación!",
    guide_h_movement: "Controles y Locomoción",
    guide_p_movement: "Domina los controles de movimiento para explorar la isla y navegar por el mar:",
    guide_lbl_keys: "Movimiento:",
    guide_desc_keys: "Usa las teclas WASD o las flechas para caminar.",
    guide_lbl_sprint: "Correr:",
    guide_desc_sprint: "Mantén presionado Shift para correr más rápido, ¡pero cuida tu barra de Energía!",
    guide_lbl_swimming: "Nadar y Bucear:",
    guide_desc_swimming: "Entra en el agua para nadar automáticamente. Mantén Espacio para subir. ¡Bucea para explorar los arrecifes!",
    guide_lbl_raft: "Navegación en Bote:",
    guide_desc_raft: "Repara el bote inicial para desbloquear el océano. Construye zattaras para explorar otras islas en el horizonte.",
    guide_h_mining: "Modificación del Terreno y Minerales",
    guide_p_mining: "El entorno es completamente destructible. Modifica la isla o excava cuevas profundas:",
    guide_lbl_digging: "Excavar:",
    guide_desc_digging: "Equipa el Pico (Slot 7) y haz Clic Izquierdo en cualquier bloque para excavar cuevas o túneles.",
    guide_lbl_sculpting: "Construir Terreno:",
    guide_desc_sculpting: "Equipa bloques de Arena o Piedra en tu hotbar y colócalos con Clic Izquierdo para hacer puentes o tapar hoyos.",
    guide_lbl_gold: "Extraer Oro:",
    guide_desc_gold: "Golpea las vetas de oro con tu Pico para extraer mineral y reparar tu bote.",
    guide_tip_mining: "Excavar bajo tierra te llevará por diferentes capas: tierra ligera, arcilla arcillosa y granito duro.",
    guide_h_crafting: "Creación y Construcción de Bases",
    guide_p_crafting: "Reúne recursos para fabricar herramientas y construir refugios:",
    guide_lbl_inventory: "Abrir Inventario:",
    guide_desc_inventory: "Presiona Tab o haz clic en la mochila para abrir el panel de creación en la derecha.",
    guide_lbl_recipes: "Recetas Básicas:",
    guide_desc_recipes: "Crea cuerdas con hojas, antorchas, sombreros de paja y fogatas para cocinar.",
    guide_lbl_building: "Construir Bases:",
    guide_desc_building: "Fabrica cimientos de madera, paredes, puertas y techos de hojas para construir refugios personalizados.",
    guide_h_weather: "Atmósfera, Estaciones y Fauna",
    guide_p_weather: "La isla tiene un ecosistema dinámico con clima variable y animales salvajes:",
    guide_lbl_weather: "Clima Dinámico:",
    guide_desc_weather: "Experimenta lluvia, nieve y tormentas tropicales. ¡Las tormentas pueden desgastar los techos de hojas!",
    guide_lbl_seasons: "Estaciones:",
    guide_desc_seasons: "Las estaciones afectan el clima. En invierno, el lago interior se congela por completo, ¡permitiéndote caminar sobre el hielo!",
    guide_lbl_hunting: "Caza y Cocina:",
    guide_desc_hunting: "¡Caza cangrejos o peces con tu Lanza (Slot 1). Enciende fogatas usando madera para cocinar carne cruda!",
    guide_lbl_fishing: "Pesca:",
    guide_desc_fishing: "Equipa la caña de pescar (Ranura 6). Párate cerca de agua profunda, mira al agua y haz clic izquierdo para lanzar. Haz clic de nuevo cuando veas un salpicón para atrapar un pez.",
    guide_lbl_smelting: "Fundición:",
    guide_desc_smelting: "Construye un Horno de Fundición. Deposita madera o carbón como combustible junto con minerales crudos (Cobre, Silicio, Titanio) para fundir lingotes y vidrio.",
    guide_lbl_farming: "Agricultura:",
    guide_desc_farming: "Fabrica un Arbusto de Bayas con 3 Bayas y colócalo. Crecerán bayas recolectables cada 60 segundos.",
    guide_lbl_canes: "Cultivo de Caña:",
    guide_desc_canes: "Fabrica una Caña de Bambú con 2 Cañas y 1 Cuerda, y colócala. Golpéala con tu lanza o hacha para recolectar caña.",
  },
  fr: {
    game_subtitle: "SURVIE ET MINAGE AU CRÉPUSCULE",
    game_desc: "Explorez une île tropicale low-poly, creusez des tunnels souterrains à la recherche d'or et évitez de vous noyer en pleine mer. Frayez-vous un chemin à travers les roches à l'aide de votre pioche et réparez le bateau.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "VEUILLEZ PIVOTER L'APPAREIL",
    rotate_warning_desc: "Ce jeu est conçu pour être joué en mode paysage (horizontal) uniquement.",
    start_btn: "DÉMARRER MOTEUR",
    continue_btn: "🔄 CONTINUER",
    controls_title: "TÉLÉMÉTRIE DES COMMANDES",
    ctrl_mv: "Mouvement FPS",
    ctrl_look: "Regarder autour",
    ctrl_dig: "Creuser / Attaquer",
    ctrl_jump: "Sauter / Nager vers le haut",
    ctrl_harvest: "Récolter minerai / ressources",
    ctrl_switch: "Changer d'outil",
    hud_objective: "OBJECTIF",
    hud_compass: "BOUSSOLE",
    hud_distance: "DISTANCE",
    hud_health: "SANTÉ",
    hud_energy: "ÉNERGIE",
    hud_hydration: "HYDRATION",
    obj_initial: "Collecter du minerai pour réparer le bateau",
    obj_progress: "Collecter du minerai pour réparer le bateau ({val}/5)",
    obj_complete: "Objectif atteint ! Bateau réparé.",
    interact_harvest: "APPUYER SUR E POUR RÉCOLTER LE MINERAI",
    interact_board: "APPUYER SUR E POUR LIRE LE TABLEAU",
    board_title: "CONSOLE DE FEEDBACK COMMUNAUTAIRE",
    board_placeholder: "Saisissez votre message ici...",
    board_submit: "TRANSMETTRE",
    board_close: "FERMER",
    msg_mined: "Minerai d'or extrait ! Ramassez-le.",
    msg_depleted: "Gisement de minerai épuisé !",
    msg_collected: "+1 Minerai d'or",
    msg_goal_complete: "Objectif de survie atteint !",
    interact_harvest_wood: "APPUYEZ SUR E POUR RAMASSER LE BOIS",
    msg_chopped: "Coupe !",
    msg_tree_felled: "Arbre abattu !",
    msg_collected_wood: "+1 Bois",
    hotbar: {
      spear: "Lance",
      axe: "Hache",
      water: "Eau",
      leaves: "Feuilles",
      rope: "Corde",
      wood: "Bois",
      pickaxe: "Pioche",
      stone: "Pierre",
      ore: "Minerai"
    },
    confirm_title: "QUITTER LA PARTIE ?",
    confirm_desc: "Voulez-vous vraiment retourner au menu principal ? Votre progression sera perdue.",
    confirm_yes: "OUI, QUITTER",
    confirm_no: "NON, CONTINUER",
    inv_title: "INVENTAIRE",
    inv_my_bag: "MON SAC",
    inv_crafting: "STATION D'ARTISANAT",
    inv_character: "PERSONNAGE",
    inv_stat_energy: "Consommation d'Énergie",
    inv_stat_hydration: "Consommation d'Hydratation",
    inv_stat_speed: "Bonus de Vitesse",
    "inv.straw_hat": "Chapeau de Paille",
    "inv.explorer_vest": "Gilet d'Explorateur",
    "inv.grass_pants": "Pantalon d'Herbe",
    "inv.wooden_boots": "Bottes en Bois",
    "inv.empty": "[Vide]",
    "recipe.rope": "3 Feuilles",
    "inv.planted_bush": "Buisson de Baies Planté",
    "recipe.planted_bush": "3 Baies",
    "inv.planted_cane": "Canne de Bambou Plantée",
    "recipe.planted_cane": "2 Cannes, 1 Corde",
    "recipe.straw_hat": "6 Feuilles, 2 Cordes",
    "recipe.grass_pants": "8 Feuilles, 3 Cordes",
    "recipe.wooden_boots": "4 Bois, 2 Cordes",
    inv_slot_feet: "PIEDS",
    inv_slot_right_hand: "MAIN DROITE",
    inv_slot_left_hand: "MAIN GAUCHE",
    
    // Game Guide Strings
    guide_btn: "📖 GUIDE DU JEU",
    guide_title: "MANUEL DE SURVIE - ARCHIPELAGO",
    guide_download_pdf: "⬇️ TÉLÉCHARGER LE PDF",
    guide_close: "FERMER",
    tab_survival: "❤️ SURVIE & HUD",
    tab_movement: "🏃 DÉPLACEMENT & EXPLO",
    tab_mining: "⛏️ MINAGE & TERRAIN",
    tab_crafting: "🛠️ ARTISANAT & BASE",
    tab_weather: "🌦️ METEO & FAUNE",
    guide_quicklink: "Appuyez sur 📖 GUIDE pour consulter le manuel complet du jeu.",
    guide_h_survival: "Indicateurs de Survie",
    guide_p_survival: "La survie sur l'île nécessite de gérer trois jauges visibles en bas à gauche de l'écran :",
    guide_lbl_health: "Santé :",
    guide_desc_health: "Diminue en cas de noyade, de faim, de froid ou d'aliments crus. Manger de la viande cuite la restaure.",
    guide_lbl_energy: "Énergie :",
    guide_desc_energy: "Consommée par le sprint, le saut et les outils. Se régénère lentement en marchant ou à l'arrêt.",
    guide_lbl_hydration: "Hydratation :",
    guide_desc_hydration: "Diminue avec le temps. Buvez de l'eau douce du lac intérieur. Boire de l'eau de mer inflige des dégâts !",
    guide_tip_title: "CONSEIL DE SURVIE :",
    guide_tip_survival: "Fabriquez des vêtements. Un chapeau de paille ou des bottes en bois réduisent l'épuisement de l'énergie et de l'eau !",
    guide_h_movement: "Commandes & Déplacement",
    guide_p_movement: "Maîtrisez les déplacements pour explorer l'île volcanique et naviguer en mer :",
    guide_lbl_keys: "Déplacement :",
    guide_desc_keys: "Utilisez les touches WASD ou les flèches pour vous déplacer.",
    guide_lbl_sprint: "Sprint :",
    guide_desc_sprint: "Maintenez Shift pour courir, mais surveillez votre jauge d'Énergie !",
    guide_lbl_swimming: "Nage & Plongée :",
    guide_desc_swimming: "Entrez dans l'eau pour nager. Maintenez Espace pour remonter. Plongez pour explorer les récifs coralliens !",
    guide_lbl_raft: "Navigation :",
    guide_desc_raft: "Réparez le bateau initial pour naviguer sur l'océan. Construisez des radeaux pour explorer les îles à l'horizon.",
    guide_h_mining: "Modelage du Terrain & Ressources",
    guide_p_mining: "L'environnement est destructible. Modelez l'île ou creusez de profonds tunnels :",
    guide_lbl_digging: "Creuser :",
    guide_desc_digging: "Équipez la Pioche (Slot 7) et faites un Clic Gauche pour creuser des grottes ou des galeries.",
    guide_lbl_sculpting: "Placer des blocs :",
    guide_desc_sculpting: "Sélectionnez des blocs de Sable ou de Pierre et placez-les avec un Clic Gauche pour bâtir des ponts.",
    guide_lbl_gold: "Minage d'Or :",
    guide_desc_gold: "Frappez les gisements d'or avec votre Pioche pour récolter les pépites et réparer le bateau.",
    guide_tip_mining: "Creuser sous terre vous fera traverser diverses couches : terre, argile et granit solide.",
    guide_h_crafting: "Artisanat & Construction",
    guide_p_crafting: "Rassemblez des ressources pour fabriquer des outils et construire des abris :",
    guide_lbl_inventory: "Inventaire :",
    guide_desc_inventory: "Appuyez sur Tab ou cliquez sur le sac à dos pour ouvrir le panneau de fabrication à droite.",
    guide_lbl_recipes: "Recettes de base :",
    guide_desc_recipes: "Créez des cordes avec des feuilles, des chapeaux de paille de protection et des feux de camp.",
    guide_lbl_building: "Construction de Base :",
    guide_desc_building: "Fabriquez des fondations en bois, des murs, des portes et des toits de feuilles pour créer votre maison.",
    guide_h_weather: "Météo, Saisons & Animaux",
    guide_p_weather: "L'île est un écosystème vivant avec une météo changeante et des animaux sauvages :",
    guide_lbl_weather: "Météo Dynamique :",
    guide_desc_weather: "Affrontez la pluie, la neige et les tempêtes. Les tempêtes peuvent abîmer les toits en feuilles !",
    guide_lbl_seasons: "Saisons :",
    guide_desc_seasons: "Les saisons influencent le climat. En hiver, le lac gèle complètement, permettant de marcher sur la glace !",
    guide_lbl_hunting: "Chasse & Cuisine :",
    guide_desc_hunting: "Chassez les crabes ou les poissons avec votre Lance (Fente 1). Allumez des feux de camp avec du bois pour cuire la viande !",
    guide_lbl_fishing: "Pêche:",
    guide_desc_fishing: "Équipez la canne à pêche (Fente 6). Tenez-vous près de l'eau profonde, regardez l'eau et faites un clic gauche pour lancer. Cliquez à nouveau quand vous voyez une éclaboussure pour attraper un poisson.",
    guide_lbl_smelting: "Fusion:",
    guide_desc_smelting: "Construisez un Fourneau de fusion. Déposez du bois ou du charbon comme combustible ainsi que des minerais bruts (Cuivre, Silicium, Titane) pour fondre des lingots et du verre.",
    guide_lbl_farming: "Agriculture:",
    guide_desc_farming: "Fabriquez un Buisson de Baies Planté avec 3 Baies et placez-le. Il fera pousser des baies récoltables toutes les 60 secondes.",
    guide_lbl_canes: "Plantation de Cannes:",
    guide_desc_canes: "Fabriquez une Canne de Bambou Plantée avec 2 Cannes et 1 Corde, et placez-la. Frappez-la avec votre lance ou votre hache pour récolter de la canne.",
  },
  de: {
    game_subtitle: "ÜBERLEBEN UND BERGBAU IM SONNENUNTERGANG",
    game_desc: "Erkunde eine Low-Poly-Tropeninsel, grabe unterirdische Tunnel auf der Suche nach Gold und vermeide es, im offenen Ozean zu ertrinken. Bahne dir mit deiner Spitzhacke den Weg durch die Felsen und repariere das Boot.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "GERÄT DREHEN",
    rotate_warning_desc: "Dieses Spiel kann nur im Querformat (horizontal) gespielt werden.",
    start_btn: "MOTOR STARTEN",
    continue_btn: "🔄 FORTSETZEN",
    controls_title: "STEUERUNGSTELEMETRIE",
    ctrl_mv: "FPS-Bewegung",
    ctrl_look: "Umschauen",
    ctrl_dig: "Graben / Angreifen",
    ctrl_jump: "Springen / Aufschwimmen",
    ctrl_harvest: "Erz / Ressourcen sammeln",
    ctrl_switch: "Werkzeug wechseln",
    hud_objective: "ZIEL",
    hud_compass: "KOMPASS",
    hud_distance: "ENTFERNUNG",
    hud_health: "GESUNDHEIT",
    hud_energy: "ENERGIE",
    hud_hydration: "HYDRATION",
    obj_initial: "Sammle Erz für Bootsreparaturen",
    obj_progress: "Sammle Erz für Bootsreparaturen ({val}/5)",
    obj_complete: "Ziel erreicht! Boot repariert.",
    interact_harvest: "DRÜCKE E, UM ERZ ZU SAMMELN",
    interact_board: "DRÜCKE E, UM DAS TABLEAU ZU LESEN",
    board_title: "COMMUNITY-FEEDBACK-TERMINAL",
    board_placeholder: "Geben Sie Ihre Nachricht ein...",
    board_submit: "SENDEN",
    board_close: "SCHLIESSEN",
    msg_mined: "Golderz abgebaut! Sammle es auf.",
    msg_depleted: "Erzvorkommen erschöpft!",
    msg_collected: "+1 Golderz",
    msg_goal_complete: "Überlebensziel erreicht!",
    interact_harvest_wood: "DRÜCKE E UM HOLZ ZU SAMMELN",
    msg_chopped: "Hack!",
    msg_tree_felled: "Baum gefällt!",
    msg_collected_wood: "+1 Holz",
    hotbar: {
      spear: "Speer",
      axe: "Axt",
      water: "Wasser",
      leaves: "Blätter",
      rope: "Seil",
      wood: "Holz",
      pickaxe: "Spitzhacke",
      stone: "Stein",
      ore: "Erz"
    },
    confirm_title: "SPIEL VERLASSEN?",
    confirm_desc: "Möchtest du wirklich zum Hauptmenü zurückkehren? Dein Fortschritt geht verloren.",
    confirm_yes: "JA, BEENDEN",
    confirm_no: "NEIN, WEITER",
    inv_title: "INVENTAR",
    inv_my_bag: "MEINE TASCHE",
    inv_crafting: "HANDWERKSSTATION",
    inv_character: "CHARAKTER",
    inv_stat_energy: "Ausdauer-Abfall",
    inv_stat_hydration: "Hydratations-Abfall",
    inv_stat_speed: "Geschwindigkeitsbonus",
    "inv.straw_hat": "Strohhut",
    "inv.explorer_vest": "Entdeckerweste",
    "inv.grass_pants": "Gras-Hose",
    "inv.wooden_boots": "Holzstiefel",
    "inv.empty": "[Leer]",
    "recipe.rope": "3 Blätter",
    "inv.planted_bush": "Gepflanzter Beerenstrauch",
    "recipe.planted_bush": "3 Beeren",
    "inv.planted_cane": "Gepflanzter Bambus",
    "recipe.planted_cane": "2 Bambus, 1 Seil",
    "recipe.straw_hat": "6 Blätter, 2 Seile",
    "recipe.grass_pants": "8 Blätter, 3 Seile",
    "recipe.wooden_boots": "4 Holz, 2 Seile",
    inv_slot_head: "KOPF",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "BEINE",
    inv_slot_feet: "FÜSSE",
    inv_slot_right_hand: "RECHTE HAND",
    inv_slot_left_hand: "LINKE HAND",
    
    // Game Guide Strings
    guide_btn: "📖 SPIELANLEITUNG",
    guide_title: "ÜBERLEBENSHANDBUCH - ARCHIPELAGO",
    guide_download_pdf: "⬇️ PDF HERUNTERLADEN",
    guide_close: "SCHLIESSEN",
    tab_survival: "❤️ ÜBERLEBEN & HUD",
    tab_movement: "🏃 BEWEGUNG & ERKUNDUNG",
    tab_mining: "⛏️ GRABEN & TERRAIN",
    tab_crafting: "🛠️ CRAFTING & BASIS",
    tab_weather: "🌦️ WETTER & FAUNA",
    guide_quicklink: "Drücke 📖 ANLEITUNG für das komplette Handbuch zu Steuerung und Gameplay.",
    guide_h_survival: "Überlebensanzeigen",
    guide_p_survival: "Das Überleben auf dieser Insel erfordert die Verwaltung dreier wichtiger Balken unten links:",
    guide_lbl_health: "Gesundheit:",
    guide_desc_health: "Sinkt durch Ertrinken, Hungern, Frieren oder rohes Essen. Gekochtes Fleisch stellt sie wieder her.",
    guide_lbl_energy: "Energie:",
    guide_desc_energy: "Verbraucht sich durch Rennen, Springen und Werkzeugnutzung. Regeneriert sich beim Gehen oder Stehen.",
    guide_lbl_hydration: "Hydration:",
    guide_desc_hydration: "Sinkt mit der Zeit. Trinke Süßwasser aus dem Binnensee. Das Trinken von Salzwasser fügt Schaden zu!",
    guide_tip_title: "ÜBERLEBENS-TIPP:",
    guide_tip_survival: "Stelle Kleidung her. Ein Strohhut oder Holzstiefel verringern den Energie- und Hydrationsverlust erheblich!",
    guide_h_movement: "Steuerung & Bewegung",
    guide_p_movement: "Meistere die Steuerung, um die Vulkaninsel und das Meer zu erkunden:",
    guide_lbl_keys: "Bewegung:",
    guide_desc_keys: "Nutze WASD oder die Pfeiltasten zum Laufen.",
    guide_lbl_sprint: "Sprinten:",
    guide_desc_sprint: "Halte die Shift-Taste gedrückt, um schneller zu rennen, aber achte auf deine Energie!",
    guide_lbl_swimming: "Schwimmen & Tauchen:",
    guide_desc_swimming: "Gehe ins Wasser, um automatisch zu schwimmen. Halte die Leertaste zum Auftauchen. Tauche nach Korallen!",
    guide_lbl_raft: "Floßnavigation:",
    guide_desc_raft: "Repariere das Startboot für Seereisen. Baue Flöße, um andere Inseln am Horizont zu erkunden.",
    guide_h_mining: "Terraforming & Erzabbau",
    guide_p_mining: "Die Welt ist vollständig zerstörbar. Forme die Insel oder grabe tiefe Tunnel:",
    guide_lbl_digging: "Graben:",
    guide_desc_digging: "Rüste die Spitzhacke (Slot 7) aus und klicke links auf Blöcke, um Höhlen oder Tunnel zu graben.",
    guide_lbl_sculpting: "Bauen:",
    guide_desc_sculpting: "Wähle Sand- oder Steinblöcke in der Schnellleiste aus und platziere sie mit Linksklick, um Brücken zu bauen.",
    guide_lbl_gold: "Golderz abbauen:",
    guide_desc_gold: "Schlage auf Golderzadern mit deiner Spitzhacke ein, um Erz zu gewinnen und das Boot zu reparieren.",
    guide_tip_mining: "Beim Graben unter der Erde durchquerst du verschiedene Schichten: helle Erde, Lehm und harten Granit.",
    guide_h_crafting: "Crafting & Basenbau",
    guide_p_crafting: "Sammle Materialien, um Werkzeuge herzustellen und Unterkünfte zu bauen:",
    guide_lbl_inventory: "Inventar öffnen:",
    guide_desc_inventory: "Drücke Tab or klicke auf den Rucksack, um das Crafting-Menü auf der rechten Seite zu öffnen.",
    guide_lbl_recipes: "Grundrezepte:",
    guide_desc_recipes: "Stelle Seile aus Blättern, schützende Strohhüte und Lagerfeuer zum Kochen her.",
    guide_lbl_building: "Basenbau:",
    guide_desc_building: "Stelle Holzfundamente, Wände, Türen und Blätterdächer her, um deine Hütte zu bauen.",
    guide_h_weather: "Atmosphäre, Jahreszeiten & Tierwelt",
    guide_p_weather: "Die Insel ist ein lebendiges Ökosystem mit dynamischem Wetter und Tieren:",
    guide_lbl_weather: "Dynamisches Wetter:",
    guide_desc_weather: "Erlebe Regen, Schnee und tropische Stürme. Stürme können Blätterdächer beschädigen!",
    guide_lbl_seasons: "Jahreszeiten:",
    guide_desc_seasons: "Jahreszeiten beeinflussen das Wetter. Im Winter friert der See komplett zu, sodass du auf dem Eis laufen kannst!",
    guide_lbl_hunting: "Jagd & Kochen:",
    guide_desc_hunting: "Jage Strandkrabben oder Fische mit dem Speer (Slot 1). Zünde Lagerfeuer an, um rohes Fleisch zu kochen!",
    guide_lbl_fishing: "Angeln:",
    guide_desc_fishing: "Rüste die Angelrute aus (Slot 6). Stelle dich ans tiefe Wasser, blicke aufs Wasser und klicke links, um auszuwerfen. Klicke erneut, wenn es spritzt, um einen Fisch zu fangen.",
    guide_lbl_smelting: "Schmelzen:",
    guide_desc_smelting: "Baue einen Schmelzofen. Lege Holz oder Kohle als Brennstoff sowie rohe Erze (Kupfer, Silizium, Titan) hinein, um Barren und Glas zu schmelzen.",
    guide_lbl_farming: "Landwirtschaft:",
    guide_desc_farming: "Stelle einen Beerenstrauch aus 3 Beeren her und platziere ihn. Alle 60 Sekunden wachsen essbare Beeren heran.",
    guide_lbl_canes: "Bambusanbau:",
    guide_desc_canes: "Stelle eine Bambuspflanze aus 2 Bambusrohren und 1 Seil her und platziere sie. Schlage mit Speer oder Axt darauf, um Bambus zu ernten.",
  },
  pt: {
    game_subtitle: "SOBREVIVÊNCIA E MINERAÇÃO AO PÔR DO SOL",
    game_desc: "Explore uma ilha tropical low-poly, cave túneis subterrâneos em busca de oro e evite se afogar no oceano aberto. Abra caminho pelas rochas usando sua picareta e conserte o barco.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "POR FAVOR ROTE O DISPOSITIVO",
    rotate_warning_desc: "Este jogo foi projetado para ser jogado apenas no modo paisagem (horizontal).",
    start_btn: "LIGAR MOTOR",
    continue_btn: "🔄 CONTINUAR",
    controls_title: "TELEMETRIA DE CONTROLE",
    ctrl_mv: "Movimento FPS",
    ctrl_look: "Olhar ao redor",
    ctrl_dig: "Cavar / Atacar",
    ctrl_jump: "Saltar / Nadar para cima",
    ctrl_harvest: "Coletar minério / recursos",
    ctrl_switch: "Mudar ferramenta",
    hud_objective: "OBJETIVO",
    hud_compass: "BÚSSOLA",
    hud_distance: "DISTÂNCIA",
    hud_health: "SAÚDE",
    hud_energy: "ENERGIA",
    hud_hydration: "HIDRATAÇÃO",
    obj_initial: "Colete minério para consertar o barco",
    obj_progress: "Colete minério para consertar o barco ({val}/5)",
    obj_complete: "Objetivo Concluído! Barco consertado.",
    interact_harvest: "PRESSIONE E PARA COLETAR MINÉRIO",
    interact_board: "PRESSIONE E PARA LER O QUADRO",
    board_title: "TERMINAL DE FEEDBACK DA COMUNIDADE",
    board_placeholder: "Digite sua mensagem aqui...",
    board_submit: "TRANSMITIR",
    board_close: "FECHAR",
    msg_mined: "Minério de ouro extraído! Colete-o.",
    msg_depleted: "Depósito de minério esgotado!",
    msg_collected: "+1 Minério de ouro",
    msg_goal_complete: "Meta de Sobrevivência Concluída!",
    interact_harvest_wood: "PRESSIONE E PARA COLETAR MADEIRA",
    msg_chopped: "Golpe!",
    msg_tree_felled: "Árvore derrubada!",
    msg_collected_wood: "+1 Madeira",
    hotbar: {
      spear: "Lança",
      axe: "Machado",
      water: "Água",
      leaves: "Folhas",
      rope: "Corda",
      wood: "Madeira",
      pickaxe: "Picareta",
      stone: "Pedra",
      ore: "Minério"
    },
    confirm_title: "ABANDONAR PARTIDA?",
    confirm_desc: "Tem certeza de que deseja voltar ao menu principal? Seu progresso será perdido.",
    confirm_yes: "SIM, SAIR",
    confirm_no: "NÃO, CONTINUAR",
    inv_title: "INVENTÁRIO",
    inv_my_bag: "MINHA MOCHILA",
    inv_crafting: "ESTAÇÃO DE CRIAÇÃO",
    inv_character: "PERSONAGEM",
    inv_stat_energy: "Consumo de Energia",
    inv_stat_hydration: "Consumo de Hidratação",
    inv_stat_speed: "Bônus de Velocidade",
    "inv.straw_hat": "Chapéu de Palha",
    "inv.explorer_vest": "Colete de Explorador",
    "inv.grass_pants": "Calças de Grama",
    "inv.wooden_boots": "Botas de Madeira",
    "inv.empty": "[Vazio]",
    "recipe.rope": "3 Folhas",
    "inv.planted_bush": "Arbusto de Bagas Plantado",
    "recipe.planted_bush": "3 Bagas",
    "inv.planted_cane": "Cana de Bambu Plantada",
    "recipe.planted_cane": "2 Canas, 1 Corda",
    "recipe.straw_hat": "6 Folhas, 2 Cordas",
    "recipe.grass_pants": "8 Folhas, 3 Cordas",
    "recipe.wooden_boots": "4 Madeira, 2 Cordas",
    inv_slot_head: "CABEÇA",
    inv_slot_torso: "TORSO",
    inv_slot_legs: "PERNAS",
    inv_slot_feet: "PÉS",
    inv_slot_right_hand: "MÃO DIREITA",
    inv_slot_left_hand: "MÃO ESQUERDA",
    
    // Game Guide Strings
    guide_btn: "📖 GUIA DE JOGO",
    guide_title: "MANUAL DE SOBREVIVÊNCIA - ARCHIPELAGO",
    guide_download_pdf: "⬇️ BAIXAR PDF",
    guide_close: "FECHAR",
    tab_survival: "❤️ SOBREVIVÊNCIA & HUD",
    tab_movement: "🏃 MOVIMENTO & EXPLO",
    tab_mining: "⛏️ ESCAVAÇÃO & TERRENO",
    tab_crafting: "🛠️ CRIAÇÃO & BASES",
    tab_weather: "🌦️ CLIMA & FAUNA",
    guide_quicklink: "Pressione 📖 GUIA para ver o manual completo de jogabilidade e controles.",
    guide_h_survival: "Indicadores de Sobrevivência",
    guide_p_survival: "A sobrevivência na ilha exige gerenciar três barras vitais visíveis no canto inferior esquerdo:",
    guide_lbl_health: "Vida:",
    guide_desc_health: "Diminui ao se afogar, passar fome, congelar ou comer comida crua. Comer carne cozida a regenera.",
    guide_lbl_energy: "Energia:",
    guide_desc_energy: "Gasta ao correr, saltar e usar ferramentas. Regenera devagar ao caminhar ou ficar parado.",
    guide_lbl_hydration: "Hidratação:",
    guide_desc_hydration: "Diminui com o tempo. Beba água doce do lago central para recuperá-la. Beber água salgada causa dano!",
    guide_tip_title: "DICA DE SOBREVIVÊNCIA:",
    guide_tip_survival: "Sempre fabrique roupas. Chapéu de palha ou botas de madeira reduzem muito a perda de energia e hidratação!",
    guide_h_movement: "Controles e Locomoção",
    guide_p_movement: "Domine os controles de movimento para explorar a ilha vulcânica e navegar nos mares:",
    guide_lbl_keys: "Movimento:",
    guide_desc_keys: "Use as teclas WASD ou setas para caminhar.",
    guide_lbl_sprint: "Correr:",
    guide_desc_sprint: "Segure Shift para correr mais rápido, mas fique de olho na barra de Energia!",
    guide_lbl_swimming: "Nadar & Mergulhar:",
    guide_desc_swimming: "Entre na água para nadar automaticamente. Segure Espaço para subir. Mergulhe para explorar recifes de coral!",
    guide_lbl_raft: "Navegação:",
    guide_desc_raft: "Repare o barco inicial para navegar no oceano. Construa jangadas para explorar outras ilhas no horizonte.",
    guide_h_mining: "Modificação de Terreno e Mineração",
    guide_p_mining: "O ambiente é destrutível. Modifique a ilha ou escave túneis profundos:",
    guide_lbl_digging: "Escavar:",
    guide_desc_digging: "Equipe a Picareta (Slot 7) e clique com o Botão Esquerdo para escavar cavernas ou túneis.",
    guide_lbl_sculpting: "Construir Terreno:",
    guide_desc_sculpting: "Selecione blocos de Areia ou Pedra na hotbar e coloque-os com Botão Esquerdo para criar pontes ou tapar buracos.",
    guide_lbl_gold: "Minar Ouro:",
    guide_desc_gold: "Acerte as veias de ouro com a Picareta para coletar minério e consertar o barco.",
    guide_tip_mining: "Escavar sob a terra revelará diferentes camadas: solo leve, argila ocre e granito escuro.",
    guide_h_crafting: "Criação e Construção de Bases",
    guide_p_crafting: "Reúna materiais para fabricar ferramentas e construir abrigos:",
    guide_lbl_inventory: "Abrir Inventário:",
    guide_desc_inventory: "Pressione Tab ou clique na mochila para abrir o painel de criação no lado direito.",
    guide_lbl_recipes: "Receitas Básicas:",
    guide_desc_recipes: "Crie cordas de folhas, chapéus de palha e fogueiras para cozinhar.",
    guide_lbl_building: "Construção de Bases:",
    guide_desc_building: "Fabrique fundações de madeira, paredes, portas e tetos de folhas para montar seu abrigo.",
    guide_h_weather: "Clima, Estações e Fauna",
    guide_p_weather: "A ilha tem um ecossistema ativo com clima mutável e vida selvagem:",
    guide_lbl_weather: "Clima Dinâmico:",
    guide_desc_weather: "Enfrante chuva, neve e tempestades tropicais. Tempestades podem danificar tetos de folhas!",
    guide_lbl_seasons: "Estações:",
    guide_desc_seasons: "As estações alteram o clima. No inverno, o lago congela totalmente, permitindo que você caminhe sobre o gelo!",
    guide_lbl_hunting: "Caça e Culinária:",
    guide_desc_hunting: "Cace caranguejos ou peixes com sua Lança (Slot 1). Acenda fogueiras com madeira para cozinhar carne crua!",
    guide_lbl_fishing: "Pesca:",
    guide_desc_fishing: "Equipe a vara de pescar (Slot 6). Fique perto da água profunda, olhe para a água e clique com o botão esquerdo para lançar. Clique novamente ao ver um respingo para pescar.",
    guide_lbl_smelting: "Fundição:",
    guide_desc_smelting: "Construa uma Fornalha de Fundição. Deposite madeira ou carvão como combustível junto com minérios brutos (Cobre, Silício, Titânio) para fundir lingotes e vidro.",
    guide_lbl_farming: "Agricultura:",
    guide_desc_farming: "Fabrique um Arbusto de Bagas usando 3 Bagas e coloque-o. Bagas colhíveis crescerão a cada 60 segundos.",
    guide_lbl_canes: "Cultivo de Cana:",
    guide_desc_canes: "Fabrique uma Cana de Bambú usando 2 Canas e 1 Corda, e coloque-a. Ataque com sua lança ou machado para colher cana.",
  },
  it: {
    game_subtitle: "SOPRAVVIVENZA E MINIERA AL TRAMONTO",
    game_desc: "Esplora un'isola tropicale low-poly, scava gallerie sotterranee alla ricerca di oro ed evita di affogare nell'oceano aperto. Fatti strada tra le rocce usando il tuo piccone e ripara la barca.",
    beta_badge: "BETA VERTICAL SLICE v0.114",
    rotate_warning_title: "RUOTA IL DISPOSITIVO",
    rotate_warning_desc: "Questo gioco è progettato per essere giocato solo in modalità orizzontale.",
    start_btn: "AVVIA MOTORE",
    continue_btn: "🔄 CONTINUA",
    controls_title: "TELEMETRIA COMANDI",
    ctrl_mv: "Movimento FPS",
    ctrl_look: "Guarda in giro",
    ctrl_dig: "Scava / Attacca",
    ctrl_jump: "Salta / Nuota su",
    ctrl_harvest: "Raccogli oro / risorse",
    ctrl_switch: "Cambia strumento",
    hud_objective: "OBIETTIVO",
    hud_compass: "BUSSOLA",
    hud_distance: "DISTANZA",
    hud_health: "SALUTE",
    hud_energy: "ENERGIA",
    hud_hydration: "IDRATAZIONE",
    obj_initial: "Raccogli oro per riparare la barca",
    obj_progress: "Raccogli oro per riparare la barca ({val}/5)",
    obj_complete: "Obiettivo Completato! Barca riparata.",
    interact_harvest: "PREMI E PER RACCOGLIERE ORO",
    interact_board: "PREMI E PER LEGGERE LA LAVAGNA",
    board_title: "TERMINALE FEEDBACK DELLA COMMUNITY",
    board_placeholder: "Scrivi il tuo messaggio qui...",
    board_submit: "INVIA",
    board_close: "CHIUDI",
    msg_mined: "Oro estratto! Raccolto.",
    msg_depleted: "Giacimento esaurito!",
    msg_collected: "+1 Oro",
    msg_goal_complete: "Obiettivo Sopravvivenza Completato!",
    interact_harvest_wood: "PREMI E PER RACCOGLIERE IL LEGNO",
    msg_chopped: "Taglio!",
    msg_tree_felled: "Albero abbattuto!",
    msg_collected_wood: "+1 Legno",
    hotbar: {
      spear: "Lancia",
      axe: "Accetta",
      water: "Acqua",
      leaves: "Foglie",
      rope: "Corda",
      wood: "Legno",
      pickaxe: "Piccone",
      stone: "Pietra",
      ore: "Oro"
    },
    confirm_title: "ABBANDONARE LA PARTITA?",
    confirm_desc: "Sei sicuro di voler tornare al menu principale? I tuoi progressi andranno perduti.",
    confirm_yes: "SÌ, ESCI",
    confirm_no: "NO, CONTINUA",
    inv_title: "INVENTARIO",
    inv_my_bag: "BORSA",
    inv_crafting: "ARTIGIANATO",
    inv_character: "PERSONAGGIO",
    inv_stat_energy: "Consumo Energia",
    inv_stat_hydration: "Consumo Acqua",
    inv_stat_speed: "Bonus Velocità",
    "inv.straw_hat": "Cappello di Paglia",
    "inv.explorer_vest": "Gilet del Esploratore",
    "inv.grass_pants": "Pantaloni d'Erba",
    "inv.wooden_boots": "Stivali di Legno",
    "inv.empty": "[Vuoto]",
    "recipe.rope": "3 Foglie",
    "inv.planted_bush": "Cespuglio di Bacche",
    "recipe.planted_bush": "3 Bacche",
    "inv.planted_cane": "Canna di Bambù Coltivata",
    "recipe.planted_cane": "2 Canne, 1 Corda",
    "recipe.straw_hat": "6 Foglie, 2 Corde",
    "recipe.grass_pants": "8 Foglie, 3 Corde",
    "recipe.wooden_boots": "4 Legno, 2 Corde",
    "inv.foundation": "Fondamenta in Legno",
    "inv.wall": "Muro in Legno",
    "inv.primitive_roof": "Tetto in Foglie",
    "inv.wood_roof": "Tetto in Legno",
    "inv.door": "Porta in Legno",
    "inv.worn_map": "Mappa Logora",
    "inv.charcoal": "Carbonella",
    "recipe.foundation": "4 Assi, 2 Legno",
    "recipe.wall": "3 Assi, 4 Bastoni",
    "recipe.primitive_roof": "4 Foglie, 2 Corde",
    "recipe.wood_roof": "3 Assi, 2 Legno",
    "recipe.door": "2 Assi, 2 Corde",
    "recipe.worn_map": "4 Foglie, 1 Carbonella",
    "inv.raw_fish": "Pesce Crudo",
    "inv.worm": "Verme",
    "inv.raw_crab": "Granchio Crudo",
    "inv.cooked_meat": "Carne Cotta",
    "inv.campfire": "Falò",
    "recipe.campfire": "4 Legno, 2 Pietra",
    interact_cook: "PREMI E PER CUOCERE LA CARNE",
    interact_harvest_crab: "PREMI E PER RACCOGLIERE IL GRANCHIO CRUDO",
    interact_harvest_fish: "PREMI E PER RACCOGLIERE IL PESCE CRUDO",
    interact_harvest_cooked: "PREMI E PER RACCOGLIERE LA CARNE COTTA",
    interact_harvest_worm: "PREMI E PER RACCOGLIERE IL VERME",
    msg_hunted_crab: "Cacciato Granchio!",
    msg_hunted_fish: "Cacciato Pesce!",
    msg_collected_worm: "+1 Verme",
    msg_cooked_crab: "Carne di Granchio Cotta!",
    msg_cooked_fish: "Carne di Pesce Cotta!",
    msg_placed_campfire: "Falò Posizionato!",
    msg_ate_cooked: "Mangiata carne cotta! +20 HP, +40 Energia",
    msg_ate_raw: "Mangiato cibo crudo! Persi 5 HP, 10 Energia",
    msg_collected_raw_crab: "+1 Granchio Crudo",
    msg_collected_raw_fish: "+1 Pesce Crudo",
    msg_collected_cooked: "+1 Carne Cotta",
    "inv.stick": "Bastone",
    "inv.cane": "Canna",
    interact_harvest_stick: "PREMI E PER RACCOGLIERE IL BASTONE",
    interact_harvest_cane: "PREMI E PER RACCOGLIERE LA CANNA",
    msg_cane_hit: "Colpita canna!",
    msg_cane_broken: "Canna spezzata!",
    msg_collected_stick: "+1 Bastone",
    msg_collected_cane: "+1 Canna",
    msg_already_hydrated: "Sei già idratato!",
    msg_drank_water: "Hai bevuto acqua! +30 Idratazione",
    interact_cook_fuel: "PREMI E PER CUOCERE / PREMI F PER AGGIUNGERE LEGNA (Fuoco: {fuel}s)",
    interact_fuel_only: "PREMI F PER AGGIUNGERE LEGNA (Fuoco: {fuel}s)",
    interact_relight: "PREMI F PER ACCENDERE (2 Pietre & 1 Foglia)",
    msg_fire_out: "IL FUOCO È SPENTO (Servono 2 Pietre & 1 Foglia)",
    msg_fire_is_out: "Il fuoco è spento! Servono pietre e combustibile per accenderlo.",
    msg_fire_full: "La capacità di legna del falò è al massimo!",
    msg_added_fuel: "Aggiunto combustibile! ({type}: +{amount}s)",
    msg_lit_fire_spark: "Hai fatto scattare le scintille con le pietre e acceso il fuoco con le foglie!",
    msg_no_fuel: "Nessun combustibile nell'inventario! (Serve Paglia, Legnetti o Legna)",
    msg_no_ignition: "Servono almeno 2 Pietre and 1 Foglia per fare la scintilla e accendere!",
    msg_world_edge: "Hai raggiunto il confine del mondo!",
    interact_harvest_log: "PREMI E PER RACCOGLIERE IL TRONCO CADUTO",
    interact_harvest_liana: "PREMI E PER RACCOGLIERE LA LIANA",
    msg_collected_log: "+1 Legno (Tronco caduto)",
    msg_collected_liana: "+1 Corda (Liana)",
    msg_need_mats_raft: "Asso. Zattera (Servono 4 Tronchi, 2 Liane, 2 Bastoni)",
    msg_press_construct: "Premi E per costruire la zattera",
    msg_press_sail: "Premi E per navigare",
    msg_press_disembark: "Premi E per sbarcare",
    msg_raft_repaired: "Zattera costruita! Pronta per navigare.",
    msg_extreme_heat: "🌡️ CALORE ESTREMO: L'idratazione scende più velocemente!",
    msg_in_lava: "🔥 NELLA LAVA! STAI SUBENDO DANNI! 🔥",
    msg_player_died: "⚠️ SEI DEFUNTO! SEI STATO RIGENERATO ALLA SPIAGGIA.",
    obj_sail_explore: "Naviga ed esplora le altre isole",
    inv_slot_head: "TESTA",
    inv_slot_torso: "BUSTO",
    inv_slot_legs: "GAMBE",
    inv_slot_feet: "PIEDI",
    inv_slot_right_hand: "MANO DESTRA",
    inv_slot_left_hand: "MANO SINISTRA",
    "inv.fishing_rod": "Canna da Pesca",
    "recipe.fishing_rod": "2 Bastoni, 2 Corde",
    "inv.sharp_stone": "Pietra Affilata",
    "inv.plank": "Asse di Legno",
    "inv.stone_block": "Blocco di Pietra",
    "inv.primitive_spear": "Lancia di Bambù",
    "inv.primitive_axe": "Accetta Primitiva",
    "inv.primitive_pickaxe": "Piccone Primitivo",
    "inv.refined_spear": "Lancia Rifinita",
    "inv.refined_axe": "Accetta Rifinita",
    "inv.refined_pickaxe": "Piccone Rifinito",
    "inv.workbench": "Banco da Lavoro",
    "inv.furnace": "Fornace di Fusione",
    "inv.lab_table": "Tavolo da Laboratorio",
    "inv.raw_silicon": "Silicio Grezzo",
    "inv.raw_copper": "Rame Grezzo",
    "inv.raw_titanium": "Titanio Grezzo",
    "inv.copper_ingot": "Lingotto di Rame",
    "inv.titanium_plate": "Piastra di Titanio",
    interact_smelt: "PREMI E PER FONDERE METALLI",
    "inv.egg": "Uovo",
    "inv.cooked_egg": "Uovo Sodo",
    interact_harvest_egg: "PREMI E PER RACCOGLIERE L'UOVO",
    interact_harvest_cooked_egg: "PREMI E PER RACCOGLIERE L'UOVO SODO",
    interact_feed_hen: "PREMI E PER NUTRIRE ROSITA (1 Verme)",
    msg_hen_laid_egg: "Rosita ha deposto un uovo!",
    msg_collected_egg: "+1 Uovo",
    msg_collected_cooked_egg: "+1 Uovo Sodo",
    msg_cooked_egg: "Uovo Cotto!",
    msg_ate_cooked_egg: "Mangiato uovo sodo! +15 HP, +30 Energia, +5 Idratazione",
    msg_fishing_wait: "Pesca in corso... attendi che abbocchi!",
    msg_fishing_bite: "UN PESCE HA ABBOCCATO! CLICCA PER TIRARE!",
    msg_fishing_caught: "Pesce pescato!",
    msg_fishing_escaped: "Il pesce è fuggito!",
    msg_fishing_early: "Hai tirato troppo presto!",
    msg_fishing_cancelled: "Pesca annullata!",
    msg_no_bait: "Serve 1 Verme come esca! Raccoglili dal gabbiano morto.",
    "inv.torch": "Torcia a Mano",
    "recipe.torch": "1 Bastone, 2 Foglie",
    "inv.berries": "Bacche Selvatiche",
    "inv.spectrometer": "Spettrometro",
    "recipe.spectrometer": "2 Rame, 1 Vetro",
    "inv.chemical_analyzer": "Analizzatore Chimico",
    "recipe.chemical_analyzer": "1 Spettrometro, 2 Corde",
    "inv.heat_suit": "Tuta Schermata",
    "recipe.heat_suit": "3 Titanio, 1 Gilet",
    "inv.silicon": "Silicio",
    "inv.titanium": "Titanio",
    "inv.copper": "Rame",
    "inv.glass": "Vetro",
    "recipe.glass": "2 Silicio",
    interact_scan: "PREMI E PER ANALIZZARE LA COMPOSIZIONE CHIMICA",
    msg_scanned: "Composizione chimica analizzata!",
    interact_harvest_berries: "PREMI E PER RACCOGLIERE LE BACCHE",
    msg_collected_berries: "+3 Bacche Selvatiche",
    msg_ate_berries: "Mangiate bacche selvatiche! +5 HP, +15 Energia, +10 Idratazione",
    
    // Game Guide Strings
    guide_btn: "📖 GUIDA E INFO",
    guide_title: "MANUALE DI SOPRAVVIVENZA ARCHIPELAGO",
    guide_download_pdf: "⬇️ SCARICA PDF",
    guide_close: "CHIUDI",
    tab_survival: "❤️ SOPRAVVIVENZA & HUD",
    tab_movement: "🏃 MOVIMENTO & ESPLO",
    tab_mining: "⛏️ SCAVO & TERRENO",
    tab_crafting: "🛠️ CRAFT & COSTRUZIONI",
    tab_weather: "🌦️ METEO & FAUNA",
    guide_quicklink: "Premi 📖 GUIDA per il manuale completo di comandi e gioco.",
    guide_h_survival: "Indicatori di Sopravvivenza",
    guide_p_survival: "La sopravvivenza su questa isola richiede la gestione di tre indicatori visibili in basso a sinistra dello schermo:",
    guide_lbl_health: "Salute (Vita):",
    guide_desc_health: "Diminuisce quando anneghi, hai fame, congeli o mangi cibo crudo tossico. Mangiare carne cotta la ripristina.",
    guide_lbl_energy: "Energia (Stamina):",
    guide_desc_energy: "Si consuma correndo, saltando e usando gli strumenti. Si rigenera stando fermi o camminando lentamente.",
    guide_lbl_hydration: "Idratazione:",
    guide_desc_hydration: "Calerebbe col tempo. Devi bere acqua dolce dal lago interno per ripristinarla. Bere acqua marina causa danni!",
    guide_tip_title: "CONSIGLIO:",
    guide_tip_survival: "Crea sempre vestiti! Un cappello di paglia o stivali di legno riducono il consumo di energia e idratazione!",
    guide_h_movement: "Comandi e Locomozione",
    guide_p_movement: "Padroneggia i comandi per esplorare l'ampia isola vulcanica e tornare in mare:",
    guide_lbl_keys: "Movimento:",
    guide_desc_keys: "Usa i tasti WASD o le frecce direzionali per camminare.",
    guide_lbl_sprint: "Corsa:",
    guide_desc_sprint: "Tieni premuto il tasto Shift per correre più veloce, consumando più energia!",
    guide_lbl_swimming: "Nuoto & Immersione:",
    guide_desc_swimming: "Entra in acqua per nuotare automaticamente. Tieni premuto Spazio per nuotare verso l'alto. Immergiti per esplorare i corali del fondale!",
    guide_lbl_raft: "Navigazione con Zattera:",
    guide_desc_raft: "Ripara la barca per sbloccare l'esplorazione oceanica. Guida le zattere per esplorare le altre isole all'orizzonte.",
    guide_h_mining: "Modellazione del Terreno ed Estrazione",
    guide_p_mining: "L'ambiente è interamente distruttibile. Modella l'isola o scava gallerie sotterranee:",
    guide_lbl_digging: "Scavo:",
    guide_desc_digging: "Seleziona il Piccone (Slot 7) e clicca col tasto sinistro per scavare grotte o gallerie nella roccia.",
    guide_lbl_sculpting: "Costruzione Terreno:",
    guide_desc_sculpting: "Raccogli blocchi di Sabbia o Pietra, selezionali nella barra rapida e posizionali per creare ponti o riparare buche.",
    guide_lbl_gold: "Estrazione Oro:",
    guide_desc_gold: "Colpisci le rocce dorate con il Piccone per estrarre l'oro grezzo necessario a riparare la barca!",
    guide_tip_mining: "Scavare in profondità ti farà attraversare vari strati terrestri: terra battuta, argilla ocra e granito scuro.",
    guide_h_crafting: "Stazione di Creazione e Costruzione",
    guide_p_crafting: "Raccogli materiali per fabbricare strumenti, indumenti protettivi o strutture:",
    guide_lbl_inventory: "Apri Inventario:",
    guide_desc_inventory: "Premi Tab o clicca sull'icona dello zaino per accedere all'inventario e alla creazione.",
    guide_lbl_recipes: "Ricette Base:",
    guide_desc_recipes: "Crea corde dalle foglie, cappelli per proteggerti dal sole e fuochi da campo per cuocere il cibo.",
    guide_lbl_building: "Costruzione Rifugi:",
    guide_desc_building: "Costruisci fondamenta, pareti, porte e tetti di legno o foglie e piazzali sull'isola per creare il tuo rifugio personalizzato!",
    guide_h_weather: "Atmosfera, Stagioni e Fauna",
    guide_p_weather: "L'isola è un ecosistema vivo caratterizzato da cambiamenti climatici, stagioni e animali selvatici:",
    guide_lbl_weather: "Meteo Dinamico:",
    guide_desc_weather: "Affronta pioggia, neve, nebbia e tempeste tropicali. Le tempeste possono danneggiare o far crollare i tetti di foglie!",
    guide_lbl_seasons: "Le Quattro Stagioni:",
    guide_desc_seasons: "Le stagioni cambiano le probabilità meteo. In inverno, il lago di montagna si congela permettendoti di camminare sul ghiaccio.",
    guide_lbl_hunting: "Caccia e Cucina:",
    guide_desc_hunting: "Caccia granchi sulla spiaggia o pesci nell'acqua bassa usando la lancia (Slot 1). Cuoci la carne cruda al fuoco da campo!",
    guide_lbl_fishing: "Pesca:",
    guide_desc_fishing: "Equipaggia la canna da pesca (Slot 6). Posizionati vicino all'acqua profonda, guarda l'acqua e clicca con il tasto sinistro per lanciare. Clicca di nuovo quando vedi uno spruzzo per catturare il pesce.",
    guide_lbl_smelting: "Fusione:",
    guide_desc_smelting: "Costruisci una Fornace. Inserisci legna o carbone come combustibile, insieme ai minerali grezzi (Rame, Silicio, Titanio) per fondere lingotti e vetro.",
    guide_lbl_farming: "Agricoltura:",
    guide_desc_farming: "Crafta un Cespuglio di Bacche con 3 Bacche e piazzalo. Produrrà bacche fresche raccoglibili ogni 60 secondi.",
    guide_lbl_canes: "Coltivare Canne:",
    guide_desc_canes: "Crafta una Pianta di Canna con 2 Canne e 1 Corda, e piazzala. Colpiscila con la lancia o l'accetta per raccogliere canne di bambù.",
  },
};

export let currentLang = 'en';

export function getTranslation(key, variables = {}) {
  const langDict = translations[currentLang] || translations['en'];
  
  // 1. Try direct lookup (in case of flat keys with dots like "inv.explorer_vest")
  let text = langDict[key];
  
  // 2. Try nested dot traversal if direct lookup failed
  if (text === undefined && key.includes('.')) {
    text = key.split('.').reduce((obj, property) => {
      return obj && obj[property];
    }, langDict);
  }
  
  // 3. Fallback to English dictionary
  if (text === undefined) {
    text = translations['en'][key];
    if (text === undefined && key.includes('.')) {
      text = key.split('.').reduce((obj, property) => {
        return obj && obj[property];
      }, translations['en']);
    }
  }
  
  // 4. Ultimate fallback to key itself
  if (text === undefined) text = key;
  
  // Replace variables like {val}
  Object.keys(variables).forEach(varName => {
    text = text.replace(`{${varName}}`, variables[varName]);
  });
  
  return text;
}

export function setLanguage(langCode) {
  if (!translations[langCode]) return;
  currentLang = langCode;
  localStorage.setItem('game_language', langCode);
  
  // 1. Update all static HTML elements marked with data-translate
  const elements = document.querySelectorAll('[data-translate]');
  elements.forEach(el => {
    const key = el.getAttribute('data-translate');
    el.textContent = getTranslation(key);
  });
  
  // 2. Update interaction prompt if it exists
  const prompt = document.getElementById('interaction-prompt');
  if (prompt) {
    // If player is looking at the board, we update dynamically elsewhere, but this is the baseline
    prompt.innerHTML = getTranslation('interact_harvest');
  }

  // 3. Update active Hotbar Labels dynamically using the player state
  import('./player.js').then(module => {
    module.player.currentLang = langCode;
    module.syncHotbarCounts();
  });

  // 4. Update dynamic Objective Text
  const objTextEl = document.getElementById('objective-text');
  if (objTextEl) {
    const slot8CountEl = document.querySelector('.hotbar-slot[data-slot="7"] .slot-count');
    let oreCount = 0;
    if (slot8CountEl) {
      const match = slot8CountEl.textContent.match(/\d+/);
      if (match && hasOre) oreCount = parseInt(match[0]);
    }
    
    if (oreCount >= 5 || objTextEl.textContent.toLowerCase().includes('complete') || objTextEl.textContent.includes('達成') || objTextEl.textContent.includes('completado') || objTextEl.textContent.includes('atteint') || objTextEl.textContent.includes('erreicht') || objTextEl.textContent.includes('concluído') || objTextEl.textContent.includes('completato')) {
      objTextEl.textContent = getTranslation('obj_complete');
      objTextEl.style.color = "#00ff88";
    } else {
      objTextEl.textContent = getTranslation('obj_progress', { val: oreCount });
      objTextEl.style.color = "#ffd700";
    }
  }

  // Update feedback board placeholder and buttons if active
  const boardPlaceholderEl = document.getElementById('feedback-input');
  if (boardPlaceholderEl) {
    boardPlaceholderEl.placeholder = getTranslation('board_placeholder');
  }
  const boardSubmitEl = document.getElementById('feedback-submit');
  if (boardSubmitEl) {
    boardSubmitEl.textContent = getTranslation('board_submit');
  }
  const boardCloseEl = document.getElementById('feedback-close');
  if (boardCloseEl) {
    boardCloseEl.textContent = getTranslation('board_close');
  }

  // Dispatch an event
  window.dispatchEvent(new CustomEvent('languagechanged', { detail: langCode }));
}

// Load default saved language if present
const savedLang = localStorage.getItem('game_language');
if (savedLang && translations[savedLang]) {
  currentLang = savedLang;
}
